### ISSUE TITLE
Offer a submission form for nontechnical users

### ISSUE THREAD

**Issue by adjkant** [2020PB/police-brutality#101]
Given how statistically unlikely first-hand documenters are to be comfortable with Github, similar to reasons mentioned in #35, I think a simple anonymous submission form that could be combed through manually (eventually made into an automated system) would be super helpful!

I would lean towards Google Forms as that will spit out an excel sheet of results constantly which could then be easily processed in CSV format or the like, but there are many solutions available for this type of stuff like Jotform and Surveymonkey among others!

**Comment by maxspencer** [comment]
I opened #35 but I think a Google Form would be good too - let's make it as easy as possible for people to contribute. I don't think there's any problem with having both in fact, provided we have a consistent format for the data once it's recorded in the repo.

**Comment by maxspencer** [comment]
@adjkant do you want to create a form/results sheet and then provide a link to it in the README?

**Comment by adjkant** [comment]
@maxspencer I've been dealing with a good deal recently but I'm going to target making this by the end of this weekend! If anyone sees this and wants to do it before, please do.

I'm also thinking about making a python script to pull submissions into PR's from a given date range / by specific ID / with some sort of flag for validity/manual checks. If I have the bandwidth, open to better suggestions on options for that for easier automation!

@2020PB @00000100-00010100 I'd love if the Google Form was done under a shared Google org or shared service account so feel free to reach out to me privately from my email in bio if needed for that or post here!

**Comment by SoumikPalFB** [comment]
I took a crack at creating a draft of this. Unfortunately I didn't put it in a company/Gsuite account, but we can definitely copy the form and use it in a company account if that's the decided route.

**Public form:** https://docs.google.com/forms/d/e/1FAIpQLScZH-LwW7E93PfyG0yJOsDkQBKnlkd0ZQ2Oe4IvpVE8CKmtOA/viewform
**Editable form:** https://docs.google.com/forms/d/1d766adpCZngoC1GQ-DscZtenlC9jrBiDXST4dw0aDOY/edit?usp=sharing
**Responses sheet:** https://docs.google.com/spreadsheets/d/1Rts5GxHiy8GVNDzczz70-KoXMSxZinivtL5qThQk8Ag/edit?usp=sharing
- The raw responses are collected in the first tab 'Form Responses 1'
- I've put the responses into the current API format in the 'API format' tab to make it easier to merge into the existing dataset if/when the time comes
- Unfortunately the Title field does not pull properly for links from Twitter. Will likely have to find an API-driven solution for this as a next step

Hopefully some of this is useful.

**Comment by andrewsnyder328** [comment]
I'm working on an Android app that consumes this data, it would be easy enough to add submission functionality if there were some API I could post JSON to.

**Comment by samgoldman** [comment]
I've created a very rough application on Heroku that lets a user submit an incident: https://police-brutality-submissions.herokuapp.com/. Code is at https://github.com/samgoldman/police-brutality-submissions.

Currently it commits the changes to a new branch on my fork. If the community approves, I plan on creating a bot account and having it automatically open pull requests to this repository (I don't want to accidentally spam the repository without anyone being aware!)

@2020PB @00000100-00010100

**Comment by maxspencer** [comment]
@samgoldman Opening an Issue rather than a PR would be a simpler/better first step in my opinion.

**Comment by maxspencer** [comment]
> @samgoldman Opening an Issue rather than a PR would be a simpler/better first step in my opinion.

Opening a PR could be a good v2 once we can assess the quality/form of reports that are coming in via that channel?

**Comment by samgoldman** [comment]
Makes sense, and definitely doable. I can work on that.

**Comment by maxspencer** [comment]
@samgoldman awesome, I have done a bit of work with the GitHub API before so if you need anyone to be a "rubber duck" then hit me up 🦆 👍

**Comment by samgoldman** [comment]
Just added functionality to open an issue to this repository. It now runs with the user @2020PB-bot.
This is what the issues will look like: https://github.com/2020PB-bot/police-brutality/issues/1
I haven't tested opening an issue on this repo yet because I'm a little wary of spamming it. Let me know what you think and if I'm good to test it out here.

**Comment by maxspencer** [comment]
@samgoldman awesome I've started watching that repo 👍

**Comment by andrewsnyder328** [comment]
@samgoldman Do you have anything against me routing to your form in a WebView from my Android app?

**Comment by samgoldman** [comment]
I'd be fine with that, I just want to do a bit more testing.

**Comment by andrewsnyder328** [comment]
Fantastic, I'll wait until you have it more ready before I develop against it. Thanks for doing this!

**Comment by adjkant** [comment]
Thank you so much @samgoldman this is exactly what I was thinking for the long term! Thanks for beating me to implementing it and doing a great job with it 💯

**Comment by samgoldman** [comment]
@adjkant Glad to help!
@andrewsnyder328 I think you're good to start integrating with it (I don't see any front end changes on the horizon). I'd hold off on making anything live until #359 is approved, to make sure every is good with the process.

**Comment by andrewsnyder328** [comment]
@samgoldman I just realized that when building this out, I will probably want to test my own implementation of it thoroughly. That would include actually submitting the form data, but I don't want to spam a bunch of test submissions. Do you have any separate test environment I can route to?

**Comment by samgoldman** [comment]
I don't right now, but I can set that up later tonight. Shouldn't take too long.

**Comment by samgoldman** [comment]
@andrewsnyder328 https://pb-submissions-dev.herokuapp.com/ is now running as a development environment. All issues created will be created on @2020PB-bot's fork.

**Comment by andrewsnyder328** [comment]
Wonderful, nice work! This will be my next priority for implementing.

**Comment by SoumikPalFB** [comment]
Awesome! Just had a few suggestions/feedback:
- Add indicators (small red asterisks maybe) next to required fields
- **Brief Title:** possible for us to scrape this from the link Meta after the submission is received and therefore make it optional? could be one less barrier to submission.
- **Date:** possible to include a date picker so there's no chance of bad data formats submitted?

**Comment by samgoldman** [comment]
@SoumikPalFB I've added the indicators. I also added some form validation (client side) that won't let the user submit incorrectly formatted dates. I'm not entirely sure how to grab a description from submitted links right now.
