### ISSUE TITLE
Creating unique IDs to match each report with a piece of media

### ISSUE THREAD

**Issue by zac-towbes** [2020PB/police-brutality#103]
It would be helpful if, as a part of the automated reporting system, unique IDs could be provided to each report so that the corresponding media could be found easily. 

If this goes on much longer, there will be too many reports to sort through manually.

**Comment by mikeycdavis** [comment]
@zac-towbes Is this still an issue? If so I'll be happy to work on it if you point me in the right direction.

**Comment by zac-towbes** [comment]
> @zac-towbes Is this still an issue? If so I'll be happy to work on it if you point me in the right direction.

@mikeycdavis I think this will be covered between #83 and #236 Thanks!
