### ISSUE TITLE
Static Web Site

### ISSUE THREAD

**Issue by codeanit** [2020PB/police-brutality#106]
Hi there. This is a good initiative :) 

I am a software developer. So would like to offer/volunteer to help, if that is needed.

We can make a static web site using JAMStack like Gatsby/Hugo or others and host it on Github.io or Netlify or other. 

And later, also for easier content creation some sort of frameworks could be used.

Let me know. Thanks.

**Comment by mnlmaier** [comment]
Maybe we can create something, I'm happy to help aswell (see #133)

**Comment by maxspencer** [comment]
@ubershmekel has created a static website based on the contents of this repo at https://2020policebrutality.netlify.app/

**Comment by maxspencer** [comment]
@codeanit I think there is a link in the README, but do open a PR to add one or make it clearer!

Those sound like they might be good suggestions, but I am not an expert on the website at all, @ubershmekel will be the best person to advise and I expect they will have notifications from this thread.

**Comment by ubershmekel** [comment]
Hi folks. I think we have more to do on the web front.

* We can make more embeds work on https://github.com/ubershmekel/2020PoliceBrutality like youtube.
* I would like to make another site or page with all the events mentioned at the same time. This would require implementing a github action that will generate a single file from this dataset. I've started the work here: https://github.com/2020PB/police-brutality/pull/110 but would love to hear more ideas.
* In general - we could make many more sites that take many more spins on this data, such as charts, etc. Don't feel limited by what I made, you can make new stuff, or collaborate on existing. Be empowered.

**Comment by vijaypemmaraju** [comment]
Hi, I’m a software engineer, and I’d love to contribute to this. I’m particularly interested in doing some data visualization, maybe in the form of heatmaps or time series? Let me know what you guys think.

**Comment by ubershmekel** [comment]
I forgot to update this thread. The structured data endpoints are live at https://github.com/2020PB/police-brutality/tree/data_build

@vijaypemmaraju please do build something! We'd like to promote anything folks build with this data at least at https://github.com/2020PB/police-brutality/wiki#sites-and-apps-built-with-the-dataset and more places.

I think it would be great to have a statistics dashboard for this dataset.

**Comment by vijaypemmaraju** [comment]
Awesome, I'll start putting something together

**Comment by SoumikPalFB** [comment]
Have created a quick GDS front end here: https://datastudio.google.com/s/oFSSsjw2kAY

Happy to add anyone as an editor if desirable, or make changes/updates.

**Comment by ubershmekel** [comment]
Thank you. This is awesome @SoumikPalFB and I've posted it to data is beautiful at - https://www.reddit.com/r/dataisbeautiful/comments/gxf8s2/police_brutality_2020_visual_dashboard/

**Comment by vijaypemmaraju** [comment]
https://vijaypemmaraju.github.io/police-brutality-data-visualizations/

Put together a couple charts here based on date and location. It works well on desktop but not so well in mobile, not sure why just yet.

**Comment by Forkk** [comment]
Hi all, I've been working on an alternate website to the current `2020policebrutality.netlify.app` one. You can find it [here](https://onebadapple.org/), and the git repo is [here](https://github.com/Forkk/BadApples).

I think the user experience on this is a good improvement over the current website. The big list of every incident on the home page gives a good impression of how prevalent these police brutality incidents truly are. Plus, each incident has its own separate page with easy next/previous buttons.

Instead of rendering the page with JavaScript, all the rendering done ahead of time using Jekyll, which improves page load times a bit.

In the coming week, I plan to add separate pages per state, so that people can still browse on a per-state basis like on the current website. It would also be nice to incorporate the data visualizations that people are making (and maybe some of my own) into the website itself, so I'll probably be looking into that as well.

Let me know what y'all think.

**Comment by andrewsuzuki** [comment]
I also made a front end / site, check it out.

:link: Live site: [**https://policebrutality.netlify.app**](https://policebrutality.netlify.app)
:wrench: Repo: [**andrewsuzuki/police-brutality-site**](https://github.com/andrewsuzuki/police-brutality-site)

Features:
- Page for each incident (using the recently-supplied ids as slugs!)
- Page for each city (+ Quick jump on home page)
- Page for each state (+ Quick jump on home page)
- Built with Gatsby (Pretty fast)
- Decent mobile responsiveness
- Tabs for each source on an incident (to reduce vertical space)

Todo:
- Incident descriptions (when available in json)
- Tags (when available)
- Call to action

**Comment by dostran4** [comment]
Closing this, since these links are in the Readme / Frontend websites gallery.
