### ISSUE TITLE
Unity between the two repos.

### ISSUE THREAD

**Issue by pb-files** [2020PB/police-brutality#107]
I have been uploading videos to the raw videos repo as people message me them on Reddit. I haven't had time to go through and update the reports in this repo.

If anyone has time to update them it would be awesome or if you have a better solution, lets hear it.

**Comment by MissNeona** [comment]
Is there a way to make sure all the rdrop areas ask people to upload their content distinctly? Or just run a bot that somehow collects any video-esque file and drops it somewhere to be sorted?

**Comment by valadect** [comment]
Related to #192 I've created a shell script that will pull all the links and download any available videos and screenshot the full web page for posterity, its a WIP but the more people with the files the better https://github.com/valadect/pbbackup

**Comment by nickatnight** [comment]
For this repo:

https://github.com/nickatnight/policebrutality.io

I'm working on an routine that will save all posts with links to s3 bucket @pb-files

**Comment by valadect** [comment]
@nickatnight that sounds awesome hopefully someone can figure out how to get working webpages of Twitter stored maybe in a WARC format and upload to wayback machine? I’ll investigate I guess.

**Comment by nickatnight** [comment]
Here is PR

https://github.com/nickatnight/policebrutality.io/pull/8

**Comment by dostran4** [comment]
Closing this, since that repo is no longer updated.
