### ISSUE TITLE
Host rest api?

### ISSUE THREAD

**Issue by nickatnight** [2020PB/police-brutality#114]
For frontend consumption maybe? Add various filter and such.

**Comment by mnlmaier** [comment]
I could help with that if needed!

**Comment by 949mac** [comment]
Linking #141

**Comment by ubershmekel** [comment]
The data build is live. Every commit to master will regenerate these files in the branch `data_build`.

* https://github.com/2020PB/police-brutality/tree/data_build
* The best data will always be at https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json
* If you want to change anything about how this data is generated then look at https://github.com/2020PB/police-brutality/tree/master/tools

Closing this issue as done. Feel free to re-open if needed.
