### ISSUE TITLE
Mace, tackling, and batons used on peaceful protesters in Seattle, WA

### ISSUE THREAD

**Issue by RooneyMcNibNug** [2020PB/police-brutality#1170]
## Location

Seattle, Washington

## Date

e.g. July 25th, 2020

## Description

Seattle Police very suddenly - and aggressively - target multiple peaceful protesters with mace, tackling, and blows from batons.

## Links

https://twitter.com/daeshikjr/status/1287288994057732098

**Comment by emarcey** [comment]
https://github.com/2020PB/police-brutality/blob/master/reports/Washington.md#police-charge-and-pepper-spray-protestors--july-25th
