### ISSUE TITLE
Happy to help: Project Management + Backend CMS + JSON REST API

### ISSUE THREAD

**Issue by 949mac** [2020PB/police-brutality#141]
I was talking with some friends yesterday saying that police brutality needs to be well documented and made public. I woke up this morning to find this.

**I have a vision for a platform with the following features:**

- [ ] An application to list grievous actions made by police to peaceful protestors  
- [ ] An interactive map where citizens can see where the hot spots are
- [ ] A wiki-of some sort to accept submissions
- [ ] A description of the individuals involved (no doxxing!), the officers involved, and the status of the officer's employment as a result of this documentation -- remember, they work for us!
- [ ] A process to decentralize the front-end application and encourage other people to get involved by hosting mirrors

I can give my time to create a backend platform to manage the submissions, approvals, etc. 
I can create a REST API
I can architect the front-end to scale
I can provide PM skills to organize multiple contributors

**What I am not:**

I'm not a designer -- (call to action!)
I prefer not to do front-end development (call to action!)

----

**Are we a good fit for each other and a community?**

My goal for the platform is to call for the full demilitarization of the police. I would like it to be done without highlighting acts of aggression by individuals. I believe showcasing actions of peaceful protestors does this in the most non-political and humancentric way possible.

Let's organize and find tech-savvy contributors if our visions and goals align.

**Comment by mnlmaier** [comment]
See my issue #133 — we could probably be a great fit! Let's talk a little more about this if you like :)

**Comment by 949mac** [comment]
Awesome! We will need this repo maintainers support and a call for other contributors. 

Pending we get a little more organized, I can have a comprehensive backend up with an API today, cached on a CDN. 

I can cover some initial costs, but we should also welcome donations to cover hosting, etc.

**Comment by nickatnight** [comment]
Discord or Slack?

**Comment by nickatnight** [comment]
@949mac what do you plan on using for backend? I got a falcon api server getting served via nginx proxy with some fancy ci/cd set up. Should have a staging server up shortly

**Comment by 949mac** [comment]
I was going to do Laravel + Nova. Then i was going to throw it on a server and add it as a pull zone on a cdn with an expire time of a few minutes, this making all api calls static. 

For zero downtime deployment, i would use Git + Deployer.

**Comment by 949mac** [comment]
> Discord or Slack?

Discord

**Comment by nickatnight** [comment]
Let's round up some troops and get the ball rolling on this :)

**Comment by 949mac** [comment]
I forked this repo and made a project board.

https://github.com/949mac/police-brutality/projects/1

Let me know if you can access it and contribute on it. Otherwise, we can use something like Trello? 

@mnlmaier - Will you volunteer design?

If anyone knows of someone who can parse through the PRs and aggregate the content, that will be important for the API.

**Comment by mnlmaier** [comment]
Seperate Post with some suggestions:

- Use two repositories, one for backend, one for frontend
- DigitalOcean hosting would be fine for me aswell
- Use very strict commit and code guidelines with pre commit linting (at least for FE code), e.g. using Husky (I can do that)
- Provide an extensive frontend readme for future contributors (I can do that if we will be using Nuxt)

**Comment by 949mac** [comment]
@mnlmaier - I just added you to the forked project

**Comment by mnlmaier** [comment]
@949mac just added some test cards – working fine. thank you!

**Comment by 949mac** [comment]
@mnlmaier - I'm good with your suggestions/standards as well.

**Comment by 949mac** [comment]
Added #160

**Comment by mnlmaier** [comment]
@949mac I have to leave for about 1h, we might spin up a discord or something later? Also I can create a basic frontend repository with a readme and guidelines on how to start coding, if we decide to stick to VueJS. Would love to!

**Comment by bobnearents** [comment]
I would love to take a look and contribute as I can. I'll be able to take a peak soon, but can't contribute much until tonight.

front-end dev btw

**Comment by mnlmaier** [comment]
@bobnearents invited!

**Comment by mnlmaier** [comment]
hey @nickatnight, great! @949mac will have to invite you, he's hosting the backend repo

**Comment by 949mac** [comment]
Hi @nickatnight, any object to Laravel/Lumen? I can purchase a Nova license.

I'm going to add similar coding guidelines.

@mnlmaier, totally. This is work belongs to our collective humanity.

**Comment by mnlmaier** [comment]
alright, will be switching my repo to public

**Comment by 949mac** [comment]
@nickatnight - Thinking about it a little more, jumping through hoops to get Nova (licensed) available to contributors might be a pain. This would be for DB management, and not necessarily needed for the overall API. With that being said, we can create the front-end manager any other way. Thoughts?

**Comment by nickatnight** [comment]
@949mac I'm not familiar with Laravel at all. What about python? Go would probably be a stretch

**Comment by nickatnight** [comment]
I scrolled through the raw video section, and it's a little unorganized. For now, a simple key/value store to hold the parsed data from the `*.md` files should be enough I think? @949mac

**Comment by mnlmaier** [comment]
@nickatnight thought about file based data storage aswell. JSON would be my favorite but YAML would also be possible for example.

My personal preference would be JSON though

**Comment by adzialocha** [comment]
I've updated @ubershmekel script and added `.json` support here: https://github.com/2020PB/police-brutality/issues/160#issuecomment-638397257 hope this helps somehow!

**Comment by 949mac** [comment]
Thanks, guys. Unfortunately, I don't have production experience with Python. 

I do have a restful API (source) ready at:

https://github.com/949mac/846-backend

Endpoints include:

- [x] GET /api/incidents
- [ ] GET /api/incidents/{id} (to do)
- [ ] GET /api/incidents/?filterby=xxx (to do)
...

This assumes the datastore is relational (MYSQL). We can store json attributes pretty easily in the tables though.

Currently, the API returns JSON.

Contributors are welcome -- I'm sorry that I don't have Python experience, but assuming we create a standard why not create a Python version? I envision this as a collective project that grants anyone access to the data.

**Comment by mnlmaier** [comment]
FE repo now public: https://github.com/mnlmaier/846-frontend/settings

@949mac great! any chance we can deploy this somewhere? would be rad to have real markers integrated later today

**Comment by mnlmaier** [comment]
also should we get reddit into the loop? 😂

**Comment by 949mac** [comment]
> FE repo now public: https://github.com/mnlmaier/846-frontend
> 
> @949mac great! any chance we can deploy this somewhere? would be rad to have real markers integrated later today

Firebase Hosting is free, initially. It might be a good fit! 

In your package.json, you can deploy on build like this:

```
  "scripts": {
    "build": "{{normal build command}}  && firebase deploy --only hosting",`
...
   }
```

Pre Reqs: 
- Install Firebase Tools (https://firebase.google.com/docs/cli)
- Run `firebase init` on your project

**Comment by 949mac** [comment]
> also should we get reddit into the loop? 😂

I think so. I'm going to get my script publically accessible and the initial content imported. I'll tell you when that is done!

**Comment by mnlmaier** [comment]
i've already got a firebase task in my project, will deploy later!

what about the backend? i would love to get the real api hooked up asap :)

**Comment by 949mac** [comment]
https://846policebrutality.b-cdn.net/api/incidents

I'm working on Lat/Lon parsing now

**Comment by mnlmaier** [comment]
@949mac can't access from FE – maybe CORS issue?

**Comment by 949mac** [comment]
Try again. I disabled CORS on the CDN.

**Comment by 949mac** [comment]
```
curl -I -X OPTIONS \
  -H "Origin: https://www.example.com" \
  -H 'Access-Control-Request-Method: GET' \
  https://846policebrutality.b-cdn.net 2>&1 | grep 'Access-Control-Allow-Origin'
```

... seems to work...

**Comment by 949mac** [comment]
@mnlmaier --

Any other desired end-points?

**Comment by mnlmaier** [comment]
working! live data on https://frontend-1750f.web.app

**Comment by 949mac** [comment]
I purchased 846policebrutality.com -- I'm willing to transfer it anyone willing to maintain it. If you think there's a better domain, let's grab it.

We can do www.domain.com and api.domain.com. If we keep 846policebrutality.com, I think we'll need to coordinate some DNS.

**Comment by mnlmaier** [comment]
@949mac cannot access endpoint from localhost – have you changed anything regarding cors?

**Comment by 949mac** [comment]
I'm looking now @mnlmaier. But I don't think anything has changed. Was localhost working before?

**Comment by mnlmaier** [comment]
yes it was – for some reason, chrome is hitting me with a CORS error now :(

**Comment by 949mac** [comment]
Hmm -- try a hard refresh? A fresh install of your app works fine for me.

![image](https://user-images.githubusercontent.com/23151962/83691126-a0d9bd80-a5a6-11ea-8221-51bb7b5846fc.png)

Edit: The joy of CORS.

**Comment by mnlmaier** [comment]
alright guys, i'll head to bed for today. thanks for the great work, let's continue tomorrow!

@949mac if you want to post this on reddit to gain some support with data quality, feel free to do so!

**Comment by 949mac** [comment]
Terrific. Thanks again for everyone's hard work!

 Let me see what we can do about introducing this back into the Reddit-sphere.

I won't be able to sit down until this evening (about 5 hours from now) -- but fingers crossed!

**Comment by 949mac** [comment]
Unfortunately, I've got to catch up on some items I neglected today. I did update the ReadMe and added a Road Map.

```
Incidents Endpoint
- [x] `HTTP GET /api/incidents` - list all incidents
- [ ] `HTTP GET /api/incidents?xx` - Filter by city, state, date range
- [ ] *Any requested end-points?*

Geolocation
- [x] Artisan command to update lat/long for all Incidents
- [ ] Automatically find lat/long on data import

Data Aggregation
- [ ] Continuous Integration of data via MD files from 2020PB/police-brutality

Data Management
- [ ] *Is there value in a CRM?*
```

It would be terrific to figure out if any other endpoints are desired and get those scoped.

Additionally, there's a python script that crunches the MD files. It would be terrific if there was a streamlined job that put those into github daily. Otherwise, I'll be looking for a way to crunch the MD files automatically in the backend. With that being said, contributions here are welcome.

**Comment by ubershmekel** [comment]
The data build is live. Every commit to master will regenerate these files in the branch `data_build`.

* https://github.com/2020PB/police-brutality/tree/data_build
* The best data will always be at https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json
* If you want to change anything about how this data is generated then look at https://github.com/2020PB/police-brutality/tree/master/tools

**Comment by 949mac** [comment]
> The data build is live. Every commit to master will regenerate these files in the branch `data_build`.
> 
> * https://github.com/2020PB/police-brutality/tree/data_build
> * The best data will always be at https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json
> * If you want to change anything about how this data is generated then look at https://github.com/2020PB/police-brutality/tree/master/tools

Wonderful! Thank you.

**Comment by nickatnight** [comment]
Wow these are great! @949mac @mnlmaier Really excited to see the traction on this. Been a hell of a day for me, but finally got this online https://github.com/nickatnight/policebrutality.io

Had to update my name servers, but http://staging.policebrutality.io/api/videos should be up soon

**Comment by nickatnight** [comment]
@ubershmekel hell ya looks good 👍

**Comment by mnlmaier** [comment]
I really think we should get this on reddit, I would be happy to get some frontend help — we could get done a lot more in a very short time! Will add a roadmap to my Readme, so others can start working on it when I'm not available :) Would like to focus on incident details next.

**Comment by mnlmaier** [comment]
You know what would also be great? Hosting RAW Video files (mp4) which we can in turn randomly play on the website (in some kind of sidebar or popup player), with the appearance of zapping through TV channels to kind of force people to see what the numbers on the map actually mean and that they resemble actual events.

WDYT @nickatnight @949mac?

**Comment by 949mac** [comment]
> You know what would also be great? Hosting RAW Video files (mp4) which we can in turn randomly play on the website (in some kind of sidebar or popup player), with the appearance of zapping through TV channels to kind of force people to see what the numbers on the map actually mean and that they resemble actual events.
> 
> WDYT @nickatnight @949mac?

Still sleeping over here :) but totally. The more visual, and easy to consume the better. 

We would need volunteers to pull the videos and to host them uniformly somewhere. I think there may have been some discussion on that already in some other threads, but I’m not entirely sure.

**Comment by 949mac** [comment]
> Wow these are great! @949mac @mnlmaier Really excited to see the traction on this. Been a hell of a day for me, but finally got this online https://github.com/nickatnight/policebrutality.io
> 
> Had to update my name servers, but http://staging.policebrutality.io/api/videos should be up soon

Looks great @nickatnight

**Comment by 949mac** [comment]
The public API is made available at https://api.846policebrutality.com/api/incidents now.

**Comment by mnlmaier** [comment]
I've deployed the new endpoint URL to firebase (https://frontend-1750f.web.app/). Should we go run the frontend on one or both domains, and get this to reddit for further volunteer to help us out? @949mac / @nickatnight ?

**Comment by mnlmaier** [comment]
Quick thoughts of what we need:

- A hoster that won't give in on political content
- Backend Devs (?)
- Data Aggregators / Cleanup-Crew (most important part imo!)
- VueJS / Nuxt frontend devs
- People who spread the word

**Comment by 949mac** [comment]
Yes, I will close this today. I've got one more API update that links all videos. It's coming shortly.

From there, we can address data clean up, etc.

**Comment by 949mac** [comment]
Here it is:

**Get all Incidents**

`HTTP GET https://api.846policebrutality.com/api/incidents`

**Get all Incidents and include Evidence** 

- Includes video source (if available)
- Includes video streams w/ download links
- Includes site, title, description, and more...

`HTTP GET https://api.846policebrutality.com/api/incidents?include=evidence`

There are a number of videos that need to be re-pulled (or at least re-attempted), and do need to update my repo and clean up my code. I'm going to be out for a few hours, but hopefully, this helps anyone! 

I'll close this after I have a chance for a final review.

**Comment by mnlmaier** [comment]
Messaged the mods. Let's see what happens! :)

**Comment by 949mac** [comment]
Okay - it looks like we can close this for now! We'll create a new ticket for anything new.

If you guys want anything else from me, let me know. I won't have to time finalize my backend repo submission until tomorrow, but I plan on adding a CLI script to download/archive the videos.

I'll jump into Discord as well.

@mnlmaier -- Thanks again for creating a fabulous frontend, and everyone else thanks for your contribution and support.
