### ISSUE TITLE
Incident in Seattle, Washington - WIP

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#1439]
## Location

Seattle, Washington

## Date

August 15th

## Description

Police pull individuals out of a van and arrest them.

Needs more context

## Links

https://twitter.com/MichaelKIRO7/status/1295231238156898304

**Comment by dostran4** [comment]
No more context seems to exist. The video itself, while cringy from the yelling, doesn't seem to indicate any visible excessive force. Closing this.
