### ISSUE TITLE
Question on Atlanta Incident Language

### ISSUE THREAD

**Issue by ZenPylon** [2020PB/police-brutality#146]
I just want to confirm that the language is correct here:

[https://github.com/2020PB/police-brutality/blob/master/reports/Georgia.md#cops-pull-people-out-of-their-car-taze-them--may-31st](https://github.com/2020PB/police-brutality/blob/master/reports/Georgia.md#cops-pull-people-out-of-their-car-taze-them--may-31st)

> Despite the woman showing resistance, the policeman grabs her and pulls her out of the car, and proceeds to taze her.

I would guess this is supposed to say "not showing resistance".

@2020PB I see that you submitted this one, can you confirm?

**Comment by gbmor** [comment]
Neither person was resisting. They actually weren't even part of the protest - they were out getting food.

The following happened (not necessarily in order, it was all very fast)

* Police broke the car windows
* Police slashed the tires
* Police tazed the woman and ripped her out of the car
* Police tazed the man multiple times before ripping him out of the car and slamming him into the pavement.
