### ISSUE TITLE
Incident in Kenosha, Wisconsin - WIP

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#1557]
## Location

Kenosha, Wisconsin

## Date

August 26th

## Description

Footage shows federal agents in unmarked cars surrounding a minivan. Officers smash a window and arrest the occupants at gunpoint.

Members of RiotKitchen allege that the individuals within were there to provide food. Police also arrested occupants of a black schoolbus at the gas station, who were traveling with the occupants of the minivan.

Waiting for more context

## Links

https://mobile.twitter.com/riotkitchen206/status/1298799200319074304
https://www.reddit.com/r/PublicFreakout/comments/ihf01g/fbi_and_kenosha_police_arresting_a_school_bus/

**Comment by dostran4** [comment]
https://www.nbcnews.com/news/us-news/kenosha-police-arrest-volunteers-who-provide-food-protesters-n1238799?cid=sm_npd_nn_tw_ma

Riot Kitchen members released on $150 bail. Their vehicles are still kept pending a police investigation. I think the fact that they broke van windows and held civilians at gunpoint based on... no evidence? Means this should be put into the repo, even with just that one original video from their Twitter.
