### ISSUE TITLE
Incident in Bedford, PA

### ISSUE THREAD

**Issue by triton11** [2020PB/police-brutality#1571]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Bedford, PA

## Date

August 25th

## Description

Protestors marching for racial justice on public street shot by local resident

## Links

https://twitter.com/WJACTV/status/1298261609706528770
https://www.pennlive.com/crime/2020/08/protesters-shooting-in-pa-caught-on-live-stream-this-dude-is-shooting-at-us.html

**Comment by emarcey** [comment]
This repo is focused on incidents of violence committed by police, not civilians. Although tragic, this event does not fit

**Comment by triton11** [comment]
Good point, closing it out!
