### ISSUE TITLE
Looking for Volunteers! We need a data aggregator

### ISSUE THREAD

**Issue by 949mac** [2020PB/police-brutality#160]
**Task:** Aggregate 2020PB items into a single CSV or Excel Spreadsheet

- [ ] Go to the link below and populate each row with the entries from each 2020PB Pull Request

https://docs.google.com/spreadsheets/d/1zEChPuDj0eTeB9cOXrJNHK3rW-aW1zohUVMm6LrN1IU/edit?usp=sharing

Perhaps multiple contributors can divide the work easily.

Assigned to: ???

If you can help, let one of the contributors know and we'll get you access to the Google Sheet.

Ref Project Board: 
https://github.com/949mac/police-brutality/projects/1

_We're petitioning this effort to be part of this repo, although we have not received a response from the original repo owner yet!_

**Comment by ChelseaHannan** [comment]
I would love to help. I'd be happy to create json files as well. It would be cool if someone could pull badge numbers from the videos with the end goal of actual repercussions for these officers.

**Comment by 949mac** [comment]
That would be great! I would prefer a CSV/Excel for ease-of-import into MySQL/Postgres. 

Are you able to copy the template I made? You can begin using that. We'll make an API to spit out the JSON.

To that point, any additional fields added would be terrific, as long as they comply with the original guidelines.

**Comment by ChelseaHannan** [comment]
Yes sounds good, I’ll copy the template and get started.

**Comment by ChelseaHannan** [comment]
I don’t see where it indicates PR# on the GitHub. Where do I find that info? Looks like the first entry on the sheet says PR# 2 so I want to make sure I’m following the right format.

**Comment by 949mac** [comment]
No problem! It's just a way to audit the list against what has been approved here. Next to Issues, look for Pull Requests:

![image](https://user-images.githubusercontent.com/23151962/83672149-acb78680-a58a-11ea-99d3-686412dc869f.png)

Then click on Closed
![image](https://user-images.githubusercontent.com/23151962/83672192-bd67fc80-a58a-11ea-99cf-e79ad0d4d2ee.png)

Then look at the PR# under the title
![image](https://user-images.githubusercontent.com/23151962/83672291-df617f00-a58a-11ea-8ffd-5869160ee020.png)

**Comment by ChelseaHannan** [comment]
Thank you! I was in the other repository that was linked on Reddit, that’s how I found this. Thank you for doing this, I’m happy to contribute to this cause. I’ve been so upset the past week about what’s happening and it feels good to fight back. I will help in any way I can so if you guys need anything just let me know. I have a little bit of experience with front-end development and some SQL knowledge, but I’m willing to learn anything necessary to contribute.

**Comment by ChelseaHannan** [comment]
Also, does it matter what order they are in? Alphabetical by state or in order of pull request?

**Comment by adzialocha** [comment]
I'm just rewriting the python script here: https://github.com/2020PB/police-brutality/pull/110 of @ubershmekel which is a helpful tool to get the data inside. Can copy it into the Google Spreadsheet in a few minutes

**Comment by 949mac** [comment]
@ChelseaHannan, it does not matter the order. Thank you.

@adzialocha, that would be terrific. Then perhaps @ChelseaHannan can review the list and add any extra details, such as badge numbers, as she sees them?

**Comment by 949mac** [comment]
@ChelseaHannan, it sounds like a scraper that will quickly iterate through each PR and scrape the content into a spreadsheet. Like a robot doing the first pass.

**Comment by ChelseaHannan** [comment]
Ok, that’s awesome. I’ll be on standby. I was working from a copy of the spreadsheet. I won’t add anymore info to the original document for the time being.

**Comment by 949mac** [comment]
Awesome. Thank you! @ChelseaHannan , want to import the CSV over into the sheet?

**Comment by adzialocha** [comment]
Not all links were parsed correctly, but I've updated the script (and sendspace files).

**Comment by mnlmaier** [comment]
One interesting thing to consider is adding geolocation (long/lat) to the cities. @949mac wdyt? would be better to do that directly on BE side instead of parsing on the frontend

**Comment by 949mac** [comment]
@mnlmaier
I agree. I can add a Job that will automatically add it based on address.

So far, it looks like we have city/state. But if there are specific addresses, we can get those lat/lons too.

**Comment by mnlmaier** [comment]
@949mac working around that with a FE package right know, until it's included in the response

**Comment by 949mac** [comment]
@adzialocha Any way to add the PR# to make the list easier to audit when updates are made?

**Comment by adzialocha** [comment]
Right now its scraping through the md files in `reports` in the master branch, no PR checking involved. I guess this can be implemented with help of the GitHub API (https://developer.github.com/v3/pulls/#list-pull-requests-files).

What is the idea behind using the PRs?

**Comment by ubershmekel** [comment]
Great work.  Let's get this list auto-generating in a github action asap. I've contacted @2020PB and hope to get an action in this repo crunching the data. My plan was to commit the generated files into a branch on this repo. That would make the files available for others to poll through the github api. 

Does anybody have a different idea or request for where to put the data after it's parsed into files?

**Comment by mnlmaier** [comment]
how quickly do you guys think we can get lat/long coordinates in there? i've set up a map which will place markers for an array of locations, just waiting for an object to be thrown in there 😬

**Comment by 949mac** [comment]
@adzialocha  -- The PR's will be useful to detach IDs. The db has internal IDs. This is useful when performing bulk updates. For example: @ChelseaHannan was going to add supplemental information.

**Comment by 949mac** [comment]
@mnlmaier - Lat/Long is in!

![image](https://user-images.githubusercontent.com/23151962/83687305-6f5df380-a5a0-11ea-87fe-c77f0574769e.png)

**Comment by elctrc** [comment]
Is the Google Sheets doc above going to be the ultimate landing spot for the data? If so, depending on how it's shared, we could hook it up to a Colab notebook in the short term to begin analysis if that seems valuable.

**Comment by 949mac** [comment]
@elctrc - That's a good question. We have an initial data import done. But for consistency, it would be nice to determine the formal structure of the data.

I'd say we're open to ideas at this point!

**Comment by elctrc** [comment]
Ok so it sounds like you've got a working script to import the data - is it doing any cleaning as well? And then the plan is to have @ChelseaHannan do a pass of adding in more metadata?

**Comment by mnlmaier** [comment]
https://frontend-1750f.web.app

thanks for the great data work guys!

**Comment by 949mac** [comment]
Yes -- so far the collabs here are not the original repo owners; so we're working somewhat independently in order to make this data more publically accessible.

With that being said, there is much value in streamlining the submissions. I'm not sure if the repo owners have put much thought into this further.

**Comment by 949mac** [comment]
> https://frontend-1750f.web.app
> 
> thanks for the great data work guys!

That's beautiful! It brings tears to my eyes. Way to go everyone.

**Comment by elctrc** [comment]
Wow. Nice work!

**Comment by elctrc** [comment]
Is there an endpoint that can be used to pull down the raw data?

**Comment by ChelseaHannan** [comment]
Looks great! Forgive me but I'm not very experienced with working with data, I don't know how to utilize the script or add metadata at this point.

**Comment by mnlmaier** [comment]
great work guys! now we can focus on design and user interactions.

@ChelseaHannan https://846policebrutality.b-cdn.net/api/incidents

**Comment by 949mac** [comment]
> Looks great! Forgive me but I'm not very experienced with working with data, I don't know how to utilize the script or add metadata at this point.

@ChelseaHannan , don't worry about the script. Let me update the sheet with the data from the script. Then in terms of improvement and metadata, you are welcome to update the sheet with any complementary and supplemental information. 

@mnlmaier - Is there anything specific you would like Chelsea to look for?

**Comment by 949mac** [comment]
@ChelseaHannan - The data is in at https://docs.google.com/spreadsheets/d/1zEChPuDj0eTeB9cOXrJNHK3rW-aW1zohUVMm6LrN1IU/edit#gid=0; 

This was created using an automated script, so it is possible that it's missing information.  Anything you can add or cleanup is greatly appreciated!

**Comment by mnlmaier** [comment]
it would make sense to use ISO or UNIX timestamps maybe?

**Comment by 949mac** [comment]
The incidents having 1900-01-01 didn't have a valid date.

As far as timestamps go, we could do that -- however, I'm not sure if there is a time component on the Incident yet.

It would be terrific if the reddit army could try to narrow some of this stuff down to improve upon the data.

**Comment by ChelseaHannan** [comment]
Nice! I’ll look over it tomorrow and make any necessary changes.

**Comment by 949mac** [comment]
Thank you, @ChelseaHannan!

**Comment by ubershmekel** [comment]
The data build is live. Every commit to master will regenerate these files in the branch `data_build`.

* https://github.com/2020PB/police-brutality/tree/data_build
* The best data will always be at https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json
* If you want to change anything about how this data is generated then look at https://github.com/2020PB/police-brutality/tree/master/tools

**Comment by elimisteve** [comment]
Here are several examples of recent police brutality from award-winning journalist Barrett Brown: https://medium.com/@barrettbrown/need-a-reason-to-smash-a-cop-9613f739149e

**Comment by ChelseaHannan** [comment]
I'm going to delete column G since E already has a formatted date.

**Comment by ubershmekel** [comment]
@949mac @ChelseaHannan I see your spreadsheet has 118 entries while https://github.com/2020PB/police-brutality/blob/data_build/all-locations.csv has 196. Did you folks happen to check what is in this one vs that? Is there data that's duplicated on the github csv or missing?

**Comment by ChelseaHannan** [comment]
Why are we building another csv here if they already have one?

**Comment by elctrc** [comment]
Forgive me but I am also going to ask: Is the purpose to take this data after it is manually cleaned/edited and populate more data on the map? Or is this for a different front end application? I ask because this is not necessarily sustainable at scale, as you begin to receive more and more data, the task of manually updating will become impossible. Is there a process in mind for joining the revised and edited set of data with the continual flow of new information?

**Comment by 949mac** [comment]
This original request was made before the data feed was ready in the readme. 

At this point, we can decide if it make sense to gather volunteers to look at the content for anything else that wasn’t automatically parsed. 

@ChelseaHannan was willing to look for supplemental information like police badge numbers, license plates, etc. 

@elctrc in terms of scale, I get it. Let’s take a step back and see what’s needed at this point. 

@mnlmaier - do you need anything else for front end content?

Otherwise, we can close this until a need arises. 

Thoughts?

**Comment by elctrc** [comment]
For sure. I am more than happy to help on the data analysis side if this is ever something desired (or if you decide you want there to be a way for users to parse the data). But that may not relate to this issue and I understand! :)

**Comment by mnlmaier** [comment]
depends on which features we will decide in the future. as a first step we should make sure that all the content is complete and that no weird things are happening (some locations are off, you can see them when zooming out in the map)

**Comment by ChelseaHannan** [comment]
@mnlmaier I really like what you've done with the map. I think you should consider creating your own separate repository for your project. I don't believe the csv in the main repo has any location coordinates. Hopefully someone can keep that updated for you, because being able to see the map is very helpful for people.

**Comment by idiosyncronaut** [comment]
I would like to propose a twitter bot that, when mentioned in conversation, submits to a data store, in an attempt to leverage twitter to easily submit abuse data. I haven't checked out the stack, but it could be a simple AWS lambda or something.

Filtering that and ensuring it turns into meaningful data will be a step to be taken.

But right now, I think the priority should be getting as much of the data stored as possible, while social media is at it's most active.

But get the data first.

**Comment by nickatnight** [comment]
The python api is finally live @949mac @mnlmaier  with full ci/cd

repo: github.com/nickatnight/policebrutality.io
api: http://api.policebrutality.io/v1/videos

@mnlmaier I could probably plug in your front end if we dockerize it

**Comment by ubershmekel** [comment]
@idiosyncronaut please open a new issue with new ideas and requests. Also, this dataset is highly edited for objectivity, and evidence. It's not an attempt to make a dump of everything. If you see something you'd like to contribute, you should make a PR to the markdown files on `master`.

@ChelseaHannan I'm sorry if there was a misunderstanding here. This github repo is managed in the markdown files on the `master` branch. It's the best way we can collaborate with 50+ contributors and verify every change as a pull request. It should be easy to make downstream datasets now, though I would recommend using the json file over the csv file.

With regards to having coordinates in our dataset - feel free to open up a separate issue if you think that's valuable.

I'm closing this mega-issue. Please feel free to comment if you think we should re-open.

**Comment by mnlmaier** [comment]
one last comment, sorry about that:

@nickatnight @949mac there's a discord server, I just asked, I am allowed to send you an invite :) any way to get in touch without posting the link publicly?

**Comment by ubershmekel** [comment]
@mnlmaier I would recommend asking them to DM you on reddit then you can check post history.
