### ISSUE TITLE
categorization to distinguish between violence and other rights violations

### ISSUE THREAD

**Issue by 00000100-00010100** [2020PB/police-brutality#164]
We already have some entries of things such as reporters being arrested. I'm just starting the conversation of how we could categorize these entries so we could easily create sub-lists. Current ideas for categories would be: physical violence, freedom of speech violation, freedom of the press violation, possibly others. There is bound to be some overlap between these categories so maybe a tagging system would be best.

**Comment by maxspencer** [comment]
+1 for some kind of system of tags, if you have some ideas, perhaps you could start drafting a concrete proposal in the OP of this issue?

**Comment by ubershmekel** [comment]
@00000100-00010100 why close this? Is there a duplicate? Seems like a valuable topic.
