### ISSUE TITLE
Backup Kansas City, MO video

### ISSUE THREAD

**Issue by Deracinate** [2020PB/police-brutality#167]
Backup the video at: https://twitter.com/weslyinfinity/status/1267321172309544960

If it goes down first, alternate link: https://www.reddit.com/r/PublicFreakout/comments/guom2g/im_sure_theyll_say_he_was_inviting_violence/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by joeydi** [comment]
Added this video to the pb-videos repo. Pull request here: https://github.com/pb-files/pb-videos/pull/4

**Comment by dostran4** [comment]
Video was backed up to that repo, so I'm closing this.
