### ISSUE TITLE
Incident in Athens, Georgia

### ISSUE THREAD

**Issue by zrs67929** [2020PB/police-brutality#1776]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Athens, Georgia

## Date

September 29 2020

## Description

Police taze an already subdued man

## Links

https://twitter.com/jordancox88/status/1311411651321753602?s=20

**Comment by SiP-C** [comment]
Was this at a protest?

**Comment by dostran4** [comment]
[Looks like he was just outside of a bar.](https://twitter.com/MariahforAthens/status/1311756603901779968)

It's definitely still Police Brutality, but it wasn't at a protest.

**Comment by emarcey** [comment]
Thanks @dostran4 

@zrs67929 I'm going to close this issue as Non Protest. Should we expand to non-protest incidents in the future, we can revisit
