### ISSUE TITLE
Mirror this repo EVERYWHERE

### ISSUE THREAD

**Issue by pydanny** [2020PB/police-brutality#191]
- gitlab
- bitbucket

All the repo hosting services, as soon as possible, should each have a mirror.

**Comment by craigjsmith** [comment]
I encourage everyone to clone this repo on their local machines, don't just depend on _the cloud_.

**Comment by mjmaurer** [comment]
Seemes like a duplicate of #32 !

**Comment by awnumar** [comment]
Links to videos should probably be replaced by archived links or the actual videos as well. I see a lot of Twitter links that could be taken down at any time.

**Comment by pydanny** [comment]
@mjmaurer Agreed, now that I see #32 I realize this is a duplicate. I'm closing this issue to reduce chatter.
