### ISSUE TITLE
Extracting videos from twitter links

### ISSUE THREAD

**Issue by JCatesPH** [2020PB/police-brutality#192]
I am going to start working on a way to extract videos from twitter links so they may be rehosted easily. I will be using python and Twitter's API.

Let me know if this is helpful or my skills can be redirected to something better.

**Comment by Ghostwaffles** [comment]
I've been using https://www.savetweetvid.com/ as a bootleg solution, it's not too efficient but it works. Maybe something similar?

**Comment by JCatesPH** [comment]
They may be using the python-twitter API in that. It would be similar, but I also wanted it to store them based on location and log data about them in json or other format.

**Comment by craigjsmith** [comment]
Take a look at https://github.com/ytdl-org/youtube-dl. Command line program for downloading video from most sites, including Twitter. Super easy to implement in any application.

**Comment by JCatesPH** [comment]
Thank you @craigjsmith ! I found it before seeing your response but am using that now.

**Comment by craigjsmith** [comment]
Nice, let me know if I can help. I think it's important that we get the videos extracted asap, many will be deleted!

**Comment by miker2049** [comment]
fyi, from the thread on #32, @hunterwilliams [shared](https://github.com/2020PB/police-brutality/issues/32#issuecomment-637886831) a node app that, if feasible, just needs to be integrated

**Comment by Ghostwaffles** [comment]
I have all the videos here downloaded and organized (somewhat), I can begin to upload them to Google Drive or somewhere else if you want

**Comment by hunterwilliams** [comment]
Yeah if you wanted it can be integrated or used to help with overall archiving process including twitter. https://github.com/hunterwilliams/link-archival - 100% made with this purpose in mind. It doesn't use any official apis which is both a plus and minus. Will continue to improve it if it seems useful or integrate if desired.

**Comment by JCatesPH** [comment]
Oh that's great @hunterwilliams . I wrote a gui tool with the hope of making submission as easy as possible but realized downloading an executable defeats the purpose. 

I am coming from the computational science side so don't worry about user interface usually. 

The tool I wrote is mostly using https://github.com/ytdl-org/youtube-dl without many additions, but I could make it add or extract links/entries from a csv file if desired.

**Comment by JCatesPH** [comment]
Perhaps the easiest option is just periodically feeding the .md files through the tool at https://github.com/hunterwilliams/link-archival

I was trying to make a low-tech person able to submit as easily as possible.

**Comment by valadect** [comment]
Ive created a shell script that will download all the videos available youtube twitter etc and also screenshot all the webpages, it will also store them in their respected geographical location. https://github.com/valadect/pbbackup

**Comment by JCatesPH** [comment]
You are the best @valadect
