### ISSUE TITLE
Original Shooting Incident in Philadelphia, PA

### ISSUE THREAD

**Issue by ubershmekel** [2020PB/police-brutality#1929]
## Location

Philadelphia, PA

## Date

2020-10-26

## Description

Police fatally shoot Walter Wallace Jr. which sparks Philadelphia protests.

## Links

https://twitter.com/AttorneyCrump/status/1320918523070337026

**Comment by emarcey** [comment]
Closing as non protest. We have the footage in Laravel for the future
