### ISSUE TITLE
Incident in LA, California

### ISSUE THREAD

**Issue by ContributingThrowaway** [2020PB/police-brutality#1932]
Police attack journalist: https://twitter.com/ShotOn35mm/status/1321352709899907073 
https://watchourcity.com/communities/about-california-southern/18-arrested-3-officers-injured-as-dodgers-fans-celebrate-historic-win-2/#:~:text=Lexis%2DOlivier%20Ray%2C%20a%20photographer,as%20a%20journalist%20multiple%20times.%E2%80%9D

(Here's the same journalist getting beaten by the same police department a few months ago: https://pressfreedomtracker.us/all-incidents/multiple-journalists-covering-protests-los-angeles-assaulted/. The LAPD is a truly a special flavor of bad.)

**Comment by emarcey** [comment]
This is at the dodgers celebrations right? I think, based on how we treated Lakers celebrations and other similar incidents, we are excluding these as they're not quite a protest. But we definitely have a bunch of footage in the archive if we are ever able to expand our scope

@SiP-C am I right on this?
