### ISSUE TITLE
Incident in NYC, NY

### ISSUE THREAD

**Issue by Aqua2765** [2020PB/police-brutality#2123]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Description

e.g. Bird's eye response to protesters, including footage of bald policeman in white short-sleeved shirt prominently featured in this NYT article: https://www.nytimes.com/interactive/2020/07/14/nyregion/nypd-george-floyd-protests.html?action=click&module=Spotlight&pgtype=Homepage

In my phone video, there is much footage before and after the pushing incident, to give context.

Link to my footage: https://www.dropbox.com/s/mhts7avufl466zw/IMG_7212.MOV?dl=0

**Comment by emarcey** [comment]
Hi @Aqua2765, would you mind providing a timestamp or trimming down the footage to the incident in question?

**Comment by Aqua2765** [comment]
2:10 - Bald policeman in short-sleeved white shirt arrives in car, exits car, walks to protesters, pushes them
2:57 - Bald policeman shoves protester (who had his hands up) hard, making him fall onto the ground (a close-up of this incident is featured in the NYT article I linked to above)
