### ISSUE TITLE
International Section beneath the State sections

### ISSUE THREAD

**Issue by KebabMalaka** [2020PB/police-brutality#214]
Events like this are occurring in response to the protests in the US and excessive force by police are being used - https://twitter.com/lovettejallow/status/1268233200473604096

**Comment by rote-culpability** [comment]
I support this action but it should be a separate fork for each country in my opinion.

**Comment by toonsevrin** [comment]
I propose we refactor the reports folder into a subfolder for each participating country (All current files would be moved to US). It feels to me like the pros of having a monorepo outweight the cons (the largest being language barriers).

**Comment by dostran4** [comment]
Closing this, as it's outside the scope of the repo. We're focusing on US content only here.
