### ISSUE TITLE
2020PB Logo

### ISSUE THREAD

**Issue by mojombo** [2020PB/police-brutality#255]
I noticed the 2020PB org doesn't have a logo, so it's showing up with the default avatar in Twitter when a link to this repo is shared. Branding is important for legitimacy, so I made you one:

![2020pb](https://user-images.githubusercontent.com/1/83839963-3ca42000-a6b2-11ea-8a67-72e6083a2766.png)

**Comment by maxspencer** [comment]
Nice work - this should be added to the README too!

**Comment by ubershmekel** [comment]
Mods are in the process of an internal discussion and reaching out to designers on reddit and outside of reddit to get more ideas for logos.

Here are some assets that have been mentioned for inspiration:

![image0](https://user-images.githubusercontent.com/77754/83905814-2e3c1f80-a717-11ea-908d-50ce66b6d92e.jpg)
![Krystle_Smith](https://user-images.githubusercontent.com/77754/83905815-2ed4b600-a717-11ea-95bd-95f0cfef2016.jpg)
![GettyImages_1216567582 0](https://user-images.githubusercontent.com/77754/83905818-2f6d4c80-a717-11ea-9f47-befba1032c0b.jpg)

**Comment by mojombo** [comment]
Awesome. Glad a discussion is underway!

**Comment by 2020PB** [comment]
I think the logo from @mojombo is pretty clean, I prefer it to the other images linked, though I think the first one could maybe be used for some kind of banner image on the Twitter account?

**Comment by pb-files** [comment]
I agree, I prefer the image from @mojombo.

**Comment by maxspencer** [comment]
Ship it :ship: :ship: :tada:

**Comment by phantomBit** [comment]
I threw these together last night

![2020PB-logo1](https://user-images.githubusercontent.com/52944582/83918784-69eedd80-a747-11ea-9f1b-e638501a22c4.png)
![2020PB-logo3](https://user-images.githubusercontent.com/52944582/83918785-69eedd80-a747-11ea-826e-f233fd8815e8.png)
![2020PB-logo2](https://user-images.githubusercontent.com/52944582/83918787-69eedd80-a747-11ea-8dc5-046355addf2e.png)

**Comment by SoumikPalFB** [comment]
![PB-2020-logo](https://user-images.githubusercontent.com/53233332/83922777-c9dc8880-a735-11ea-8a6d-cb6552eeb641.png)

**Comment by quangkieu** [comment]
@SoumikPalFB Your logo kind of hard to see in dark background

![image](https://user-images.githubusercontent.com/4308312/83926011-a5dd6f00-a756-11ea-85f4-341bb0cf9a1e.png)

**Comment by owlsinger189** [comment]
Thank you all for your hard work. Here is my submission for a logo/emblem. My goal was to connect BLM or Black Power with "we are watching you."
![watch-01](https://user-images.githubusercontent.com/66497296/83926127-978b5500-a74e-11ea-87df-dc59cf4353c0.jpg)
![watch-03](https://user-images.githubusercontent.com/66497296/83926128-99551880-a74e-11ea-83a9-e25128bcb0eb.jpg)

**Comment by phantomBit** [comment]
O I like that, though I would add a light outline so it can be seen on black background. But yeah. That's cool

**Comment by SoumikPalFB** [comment]
> @SoumikPalFB Your logo kind of hard to see in dark background
> 
> ![image](https://user-images.githubusercontent.com/4308312/83926011-a5dd6f00-a756-11ea-85f4-341bb0cf9a1e.png)

Good call, sorry about that. Here's a version with the white blocked out.

![PB2020-Logo](https://user-images.githubusercontent.com/53233332/83932496-c22ddb80-a757-11ea-90cd-4f79a0f1541e.png)

**Comment by SoumikPalFB** [comment]
> Thank you all for your hard work. Here is my submission for a logo/emblem. My goal was to connect BLM or Black Power with "we are watching you."
> ![watch-01](https://user-images.githubusercontent.com/66497296/83926127-978b5500-a74e-11ea-87df-dc59cf4353c0.jpg)
> ![watch-03](https://user-images.githubusercontent.com/66497296/83926128-99551880-a74e-11ea-83a9-e25128bcb0eb.jpg)

Really like the simplicity of the b&w one! Nice work!

**Comment by tawfl** [comment]
Here's some more for you if you're interested! The top one is the main version, then there's a square version, a shortened version, a square shortened version and a twitter mockup. Full album here: https://imgur.com/a/0FuYKXQ
![Artboard 1](https://user-images.githubusercontent.com/66502064/83933457-9e17dc00-a7e3-11ea-87c7-a9bdcbba6e2a.png)

**Comment by RyanScottLewis** [comment]
"PB" is a little too succinct. Those are beautiful when not acronymized (full and square versions).

**Comment by andrewsnyder328** [comment]
@tawfl Do you mind if I use the 2020 Police Brutality square icon in my Android app? Is there any sort of license associated?

**Comment by tawfl** [comment]
@andrewsnyder328 go for it!

**Comment by ubershmekel** [comment]
@owlsinger189 do you have a vector version of your image?

**Comment by owlsinger189** [comment]
@ubershmekel Here is the .ai file. The first box still has outlines so you can play with the shapes, the other two have been merged with a grunge texture I was trying. I would love to see what you can come up with, I don't usually get to collaborate on design and I'm excited to be working with all of you on this important project.
[watch.ai.zip](https://github.com/2020PB/police-brutality/files/4741157/watch.ai.zip)

**Comment by owlsinger189** [comment]
@ubershmekel Here is the design as an .eps, just in case you aren't using AI. Thanks!
[watch-pb2020.eps.zip](https://github.com/2020PB/police-brutality/files/4741164/watch-pb2020.eps.zip)

**Comment by indil47** [comment]
@owlsinger189 Hi!  I would like to discuss things a bit further with you... can I contact you via twitter or something to be able to DM you?  Can't really do so on a public forum such as this.  Thanks!

**Comment by indil47** [comment]
@owlsinger189 Oh, FYI, I'm on the project management side of the team.  :)

**Comment by owlsinger189** [comment]
@indil47 thanks for reaching out! Please email whowatches0000@gmail.com and I can follow up with a portfolio from my personal account. Thanks for keeping things safe and anonymous, and I appreciate your help in getting me involved!

**Comment by indil47** [comment]
Absolutely!  I'll be contacting you soon...

**Comment by junkytunk** [comment]
With what knowledge I have of Photoshop, I put the following design pitch together for someone with better skills and eyes to play with and improve upon.

The shapes are meant to represent two people: 1) up top (a cop) raising their hands to beat the person below them 2) a victim of police brutality raising their hands to show that they are compliant and not a threat. The victim's face being the aperture of a camera lens to signify the recordings of these events. 

Love what y'all are doing here and I hope this can help in some way.

![Police Brutality logo](https://user-images.githubusercontent.com/66551743/83965221-05836980-a880-11ea-89ea-5c9f141c8229.png)

**Comment by owlsinger189** [comment]
@junkytunk I really like how you incorporated the camera and I like your text work! I had already been compiling these thumbnails, feel free to download the zip and use anything you'd like. Thanks for pitching in!

![PB2020 Logo Thumbnails](https://user-images.githubusercontent.com/66497296/83979548-c9c6bf00-a8d4-11ea-81b9-4b494ccf9427.png)

[PB2020 Logo.zip](https://github.com/2020PB/police-brutality/files/4742892/PB2020.Logo.zip)

**Comment by tawfl** [comment]
> @junkytunk I really like how you incorporated the camera and I like your text work! I had already been compiling these thumbnails, feel free to download the zip and use anything you'd like. Thanks for pitching in!
> 
> ![PB2020 Logo Thumbnails](https://user-images.githubusercontent.com/66497296/83979548-c9c6bf00-a8d4-11ea-81b9-4b494ccf9427.png)
> 
> [PB2020 Logo.zip](https://github.com/2020PB/police-brutality/files/4742892/PB2020.Logo.zip)

@owlsinger189 FYI the fonts I used were Futura condensed bold, and Georgia bold/regular. I can send you the .ai if you need :)

**Comment by dostran4** [comment]
@ubershmekel Can we close this? Seems like logos have been put in their respective slots.
