### ISSUE TITLE
Can some more people have the ability to approve/merge PRs?

### ISSUE THREAD

**Issue by maxspencer** [2020PB/police-brutality#261]
The longer PRs remain open the greater the chance of there being duplicates and merge conflicts. Some users may feel reluctant to open many PRs at once when they can see there's a backlog. Minor updates/edits may be discouraged as well.

I'm not advocating complete open-season, but a process for steadily adding more users with write access seems necessary for the health of the repo.

There would be benefits from having people in different time zones too. They'd be able to merge PRs too to prevent a build-up while you folks in the US are working/sleeping!

🙋‍♂️ I'm in the UK and am happy to help 🇬🇧 I use Git/GitHub professionally every day - that's no guarantee I won't make [mistakes](https://github.com/2020PB/police-brutality/issues/168#issuecomment-638400887), but I will take care to ensure that contributions adhere to the guidelines.

**Comment by kaznatcheev** [comment]
I think that this is a good idea. I am also based in the UK and happy to help.

**Comment by 2020PB** [comment]
@maxspencer added you based on your frequent commits and github activity, thanks for all the help.

I'm not 100% sure how to assess who to add, we have just been doing it so far based on activity on the subreddit and github, and I do not have much experience managing a large popular repository like this, especially one with material which would be so likely to attract bad actors. If anyone would like to propose some kind of criteria I think that would be great.

**Comment by maxspencer** [comment]
@2020PB thanks for adding me, I'm reviewing PRs now :+1: Happy to help!

I think you make a good point about ensuring "bad actors" can't cause too much trouble. I think there are some useful settings you can enable, will see what I can recommend.

**Comment by maxspencer** [comment]
> @2020PB thanks for adding me, I'm reviewing PRs now +1 Happy to help!

I'm going to assign myself to any PRs I'm involved in reviewing/merging so you can see which ones are being dealt with.

**Comment by d1ll0n** [comment]
Excellent, thank you!
