### ISSUE TITLE
Add pytest unit tests to `data_builder`

### ISSUE THREAD

**Issue by ShaynaCummings** [2020PB/police-brutality#280]
It would be great to have some unit tests for the methods in `data_builder` to help find edge cases in data formatting. I'm happy to start up a suite using pytest - please let me know if I should proceed and I'll start a PR.

**Comment by 2020PB** [comment]
This sounds like a great idea - tagging @samgoldman and @ubershmekel for input.

**Comment by ShaynaCummings** [comment]
Super! This is the kind of thing I was thinking: 
https://github.com/2020PB/police-brutality/compare/master...ShaynaCummings:add-tests

**Comment by samgoldman** [comment]
I've only contributed a small amount to the script, but I always think testing is a great idea. Let me know if you want me to do anything.

**Comment by ubershmekel** [comment]
@ShaynaCummings this looks good to me. If you're available for more test ideas, here are some that would rely on running `process_md_texts`:

* No empty `links` fields.
* No empty `state` fields.
* No empty `name` fields.
* More than 200 records found.

**Comment by ShaynaCummings** [comment]
@ubershmekel still working on a few more of these cases, but I was wondering if there are future plans for handling invalid or non-parsable entries beyond writing to stdout? I put some specific examples as failing or unfinished tests in the draft PR if you want to take a look.

**Comment by ubershmekel** [comment]
@ShaynaCummings if you prefer - you can just commit the tests and I'll hook them up to the github action, or you can cover that in your PR as well.

https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

To test the action, fork the repo, author your new test action, make a PR to your fork, and check if the tests pass or don't based on what's in the PR. The PR should show a nice big red X or green circle I think if everything got glued. There might even be a way to output exactly which tests failed on which data points.
