### ISSUE TITLE
JSON/YAML/CSV Formats

### ISSUE THREAD

**Issue by RyanScottLewis** [2020PB/police-brutality#317]
Could have files for each state or a global "master" file collecting all of the links in a machine readable format. If you like the idea, I'll collect it myself and PR it but I'd like to hear opinions. :v: 
Edit: I understand the Python tools build JSON and CSV from the Markdown files but that feels backwards and requires users to install Python and run the builder to generate these files. Maybe run the builder with build automation and add those generated files to the repo to be more easily accessible?

**Comment by 00000100-00010100** [comment]
Every time a commit happens this branch that gets updated: https://github.com/2020PB/police-brutality/tree/data_build

**Comment by ubershmekel** [comment]
For example - this always has the live data: https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json

**Comment by ubershmekel** [comment]
No response from @RyanScottLewis so I assume he's good with the answers. Feel free to reopen if needed.
