### ISSUE TITLE
Incident in NYC, NY

### ISSUE THREAD

**Issue by milestucker95** [2020PB/police-brutality#318]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

NYC, NY

## Date
May 31st

## Description

Police pulls down black man's face mask and pepper sprays him
## Links

https://twitter.com/ajrupchandani/status/1266889115288711168?s=21

**Comment by Ghostwaffles** [comment]
Incident is already in NY as "Police spray unarmed man with pepperspray and shoot him in the face with a teargas canister", however this appears to be the original source of the video.
