### ISSUE TITLE
Incident in Grand Rapids, MI

### ISSUE THREAD

**Issue by milestucker95** [2020PB/police-brutality#319]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Grand Rapids, MI

## Date

June 1st

## Description

May yells at police and they pepper spray him. Then they shoot him in the face with a tear gas canister. 

## Links

https://twitter.com/greg_doucette/status/1267281344649932806?s=21

**Comment by Ghostwaffles** [comment]
Incident is already in MI as "Police spray unarmed man with pepperspray and shoot him in the face with a teargas canister"

**Comment by MicahRCM** [comment]
Yes, this was already added here: https://github.com/2020PB/police-brutality/commit/7952e58c380646da4402c13ec177010efb654477
