### ISSUE TITLE
Incident in NYC, NY

### ISSUE THREAD

**Issue by milestucker95** [2020PB/police-brutality#320]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

NYC,NY

## Date

June 3rd

## Description

Police randomly beating pedestrian

## Links

https://twitter.com/youranoncentral/status/1268377775649374210?s=21

**Comment by Ghostwaffles** [comment]
Incident is already in NY as "Man walking his bike beaten by officers with batons"
