### ISSUE TITLE
Indianapolis, IN

### ISSUE THREAD

**Issue by danopolis** [2020PB/police-brutality#343]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Indianapolis

This incident: https://github.com/2020PB/police-brutality/blob/master/reports/Indiana.md#police-beat-woman-with-batons-and-shoot-pepper-balls-shove-another-to-the-ground--june-1st

Was also reported in the Washington Post.

## Links

https://www.washingtonpost.com/national/protests-police-brutality-video/2020/06/05/a9e66568-a768-11ea-b473-04905b1af82b_story.html

**Comment by 00000100-00010100** [comment]
Added in #353 thank you
