### ISSUE TITLE
Twitter video google doc

### ISSUE THREAD

**Issue by LizCFox** [2020PB/police-brutality#397]
On mobile so cannot check this the way I want to; but here is a google doc created by others, if someone could merge the info and remove duplicates? 

https://docs.google.com/spreadsheets/d/1YmZeSxpz52qT-10tkCjWOwOGkQqle7Wd1P7ZM1wMW0E/htmlview?usp=sharing&sle=true&pru=AAABcrGLTFk*l-vSpfnchJvot43-LYcZ1w

**Comment by carlnewton** [comment]
I guess the fastest way to do this is to collaborate a mapping between the two. I have started a spreadsheet here: https://docs.google.com/spreadsheets/d/1ws4X1JIPx7JquguxhJyrWJIJZt2c7sbagxx2dcZhdoA/edit?usp=sharing

Please contribute!

**Comment by carlnewton** [comment]
I have also spotted that other incident collection projects exist, so [I have created a repo](https://github.com/carlnewton/blm-protest-project-list) which will list all lists in hopes that we can make everyone aware of other projects, and as a result begin to consolidate if those responsible for their projects would like to.

**Comment by dostran4** [comment]
Closing this. We tend to put up Greg's stuff anyways.
