### ISSUE TITLE
Suggested textual change for frontpage of 2020policeprutality.com: riots --> protests

### ISSUE THREAD

**Issue by FrankvanCaspel** [2020PB/police-brutality#401]
Hey all, hope this is the right spot to put this. On the frontpage of 2020policebrutality.com it currently says:

"This interactive map showcases incidents with police enforcing unecessary actions against protesters during the Riots after the murder of George Floyd."

I'd suggest removing the typo in 'unecessary' and changing 'Riots' (capital R?) to 'protests'. Naming them 'riots' undercuts the idea that police enforcement is unnecessary. To prevent having 'protest' twice in then sentence I'd then also suggest replacing 'protesters' with 'citizens'. Like so:

"This interactive map showcases incidents with police enforcing unnecessary actions against citizens during the protests after the murder of George Floyd."

**Comment by samgoldman** [comment]
I think https://github.com/mnlmaier/846-frontend is the repository for that website. You might want to open an issue there.

**Comment by FrankvanCaspel** [comment]
Thanks Sam, will do! I'll close this one now.
