### ISSUE TITLE
Make an "All States" Category

### ISSUE THREAD

**Issue by BennetLeff** [2020PB/police-brutality#42]
I think it may be helpful to add an all category so that people can view everything without having to click on individual markdown files. I'd be happy to make a PR for it. I do realize this would require editing two markdown files per commit but it seems worth it.

**Comment by 2020PB** [comment]
Great idea, we had a recent suggestion about this on Reddit as well. The person who made the suggestion recommended [using this](https://help.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data) which I am not really familiar with. Want to take a crack at it?

**Comment by mrweiner** [comment]
@2020PB this would a bit more complex of a solution, but I do Drupal dev which has pretty powerful handling for forms and the ability to assign perms for content moderation. Would it be helpful to spin something up for y'all to accept form submissions, add moderators, etc?

**Comment by ubershmekel** [comment]
@2020PB I'll make an action that will combine all the markdown into one CSV file and one MD file.

**Comment by maxspencer** [comment]
+1 to the idea of being able to *view* all the incidents in one list like that, but it's definitely not sensible to have two copies of each incident that need to be manually kept in sync in the repo.

**Comment by ubershmekel** [comment]
@maxspencer it won't be double booking. We will have files constantly generated from the current markdown system.

**Comment by maxspencer** [comment]
@ubershmekel perfect 👍

**Comment by emarcey** [comment]
@ubershmekel did this a while ago 👍

**Comment by ubershmekel** [comment]
This is the link to the combine markdown file: https://github.com/2020PB/police-brutality/blob/data_build/all-locations.md
