### ISSUE TITLE
We need more people to review pull requests

### ISSUE THREAD

**Issue by ubershmekel** [2020PB/police-brutality#426]
We need help making sure we merge quality changes quickly, and make PRs from sources that are popping up.

* @MicahRCM
* @AIDE-D-BH 
* @Ghostwaffles
* @ZenPylon
* @Samar-droid25
* @samgoldman

I'm reaching out to you because I noticed you have a lot of commits in the repo. If you'd like to join us and be a reviewer/contributor/curator/merger on this repo, we'd love to have that conversation. What do y'all think?

**Comment by Ghostwaffles** [comment]
I'd be fine with joining

**Comment by samgoldman** [comment]
I'd be willing to help. I don't have much experience moderating content, but I'd be willing learn.

**Comment by ZenPylon** [comment]
I'd love to contribute.  Please let me/us know how we can be helpful in reviewing/curating!

**Comment by breadbored** [comment]
I'd like to help too. I made this [police brutality timeline](https://bread.codes/PoliceBrutality/) that's getting 10s of thousands of visitors and I really want to make sure it's updated as people see it.

I was just alerted that Indianapolis had some very violent police last weekend that resulted in 2 deaths and it's not being reported on the list. I think more people being able to coordinate the Pull Requests over Slack or Discord could be beneficial to completing the list.

**Comment by ubershmekel** [comment]
@ZenPylon @samgoldman @Ghostwaffles can you email me (ubershmekel at gmail) so we have a direct line and I'll send you invites to our discord?
