### ISSUE TITLE
Incident in San Diego, California

### ISSUE THREAD

**Issue by Jellyfish484** [2020PB/police-brutality#437]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

San Diego, CA

## Date

5/31/2020

## Description

One set of police kettle protestors toward another set of police, so the second set of police can shoot them

## Links

https://youtu.be/6uNySPSwhAI

**Comment by emarcey** [comment]
@Jellyfish484 where are you getting the 5/31 date? I'm having trouble finding it anywhere

**Comment by Jellyfish484** [comment]
I asked the person who posted the video on Reddit.

**Comment by emarcey** [comment]
Would you mind sending me the reddit link? 

Did you ask in the comments or a DM?

**Comment by Jellyfish484** [comment]
Sure! Here is the link. The reply should be nested below it. I will make
sure to add links to any future interactions I have to get clarification on
dates.

https://www.reddit.com/r/2020PoliceBrutality/comments/gynpd8/police_block_off_sidewalks_and_start_shooting_at/ftdkbcp?utm_source=share&utm_medium=web2x

**Comment by emarcey** [comment]
No worries, thanks for verifying. I just wanted to double check on the date. Thanks!
