### ISSUE TITLE
Incident in Seattle, WA

### ISSUE THREAD

**Issue by Jellyfish484** [2020PB/police-brutality#441]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Seattle, Washington

## Date

Unknown

## Description

Police use tear gas on protestors despite a ban on tear gas by the mayor.

## Links

https://www.reddit.com/r/2020PoliceBrutality/comments/gycscp/cant_go_1_day_without_teargaslighting_us/?utm_source=share&utm_medium=web2x

https://www.forbes.com/sites/jemimamcevoy/2020/06/08/seattle-police-use-tear-gas-against-protestors-despite-city-ban/#7e98a1d5b4bc

**Comment by haydenbspence** [comment]
https://github.com/2020PB/police-brutality/pull/442
