### ISSUE TITLE
Incident in Huntsville, AL

### ISSUE THREAD

**Issue by Jellyfish484** [2020PB/police-brutality#444]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Huntsville, AL

## Date

Unknown

## Description

Woman is shot five times with rubber bullets while following police directive to disperse.

## Links

https://www.reddit.com/r/2020PoliceBrutality/comments/gyo2fh/huntsville_al_woman_documents_herself_struggling/?utm_source=share&utm_medium=web2x

**Comment by emarcey** [comment]
Incident has been added in https://github.com/2020PB/police-brutality/pull/449

Thanks for the submission
