### ISSUE TITLE
Minneapolis, MN

### ISSUE THREAD

**Issue by rchurchwell** [2020PB/police-brutality#456]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Minneapolis, MN

## Date

May 30th

## Description

Videos Show Cops Slashing Car Tires at Protests in Minneapolis 

## Links

https://www.motherjones.com/anti-racism-police-protest/2020/06/videos-show-cops-slashing-car-tires-at-protests-in-minneapolis/

**Comment by haydenbspence** [comment]
I've confirmed this incident is already documented in Minnesota.md
