### ISSUE TITLE
Metro Buses used to transport detainees Los Angeles, CA

### ISSUE THREAD

**Issue by rymndng** [2020PB/police-brutality#457]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Los Angeles
Downtown LA
Hollywood

## Date

Fri May 30 - Mon Jun 1

## Description

LAPD using Metro buses to transport arrested peaceful protestors past curfew and after transit service shutdown on Sat May 31.

## Links

https://twitter.com/LAist/status/1267006683596775424

https://twitter.com/jimw/status/1267666982544932866

https://twitter.com/MattHjourno/status/1267658943486017536

@lapdtransit Instagram post was deleted

Official Metro statement
https://thesource.metro.net/2020/06/01/metro-explains-decision-to-suspend-service-saturday-night-and-law-enforcements-use-of-our-buses/

![image](https://user-images.githubusercontent.com/66644549/84075143-80d04280-a988-11ea-8273-5ff1d450c928.png)
![image](https://user-images.githubusercontent.com/66644549/84075160-862d8d00-a988-11ea-9732-603220faf0a8.png)
![image](https://user-images.githubusercontent.com/66644549/84075174-8b8ad780-a988-11ea-90db-4ee643101a09.png)
![image](https://user-images.githubusercontent.com/66644549/84075184-8f1e5e80-a988-11ea-80b2-a37bc8a085cc.png)

**Comment by haydenbspence** [comment]
https://github.com/2020PB/police-brutality/pull/459

I'm unsure exactly how to link link the pull request and issue to resolve. Apologies.
