### ISSUE TITLE
Incident in Denver, Colorado 

### ISSUE THREAD

**Issue by donnellca** [2020PB/police-brutality#460]
## Location

Denver, Colorado

## Date

On or before May 29th

## Description 

Police toss tear gas into peaceful protesters

## Link 

https://www.reddit.com/r/Denver/comments/gslcxb/the_moment_the_cops_tear_gassed_the_protesters_at/

**Comment by haydenbspence** [comment]
Added https://github.com/2020PB/police-brutality/pull/462

**Comment by donnellca** [comment]
> Added #462

Just out of curiosity, does that mean this is incident 462, or this is the 462nd suggestion/edit?

**Comment by haydenbspence** [comment]
That should be the pull request 462. My apologies I was unfamiliar with how to link issues and pulls and had to figure that out.

**Comment by donnellca** [comment]
No worries, I was just curious. Thank you.
