### ISSUE TITLE
Incident in Brooklyn, New York

### ISSUE THREAD

**Issue by Jellyfish484** [2020PB/police-brutality#463]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Brooklyn, New York

## Date

June 6

## Description

Multiple police officers tackle a cyclist on a Black Lives Matter group ride. The man is repeatedly punched in the head by an officer and as the person filming shouts at him not to resist, he shouts "I'm not!"

## Links

https://www.reddit.com/r/Brooklyn/comments/gy40fz/nypd_aggressively_arrest_cyclist_on_blm_group_ride/?utm_source=share&utm_medium=web2x

**Comment by haydenbspence** [comment]
Submitted pull request. Figured out how to link them! For anyone wondering, put # and the number of the issue in title for the push '#463'.
