### ISSUE TITLE
Incident in Decatur, AL

### ISSUE THREAD

**Issue by rchurchwell** [2020PB/police-brutality#484]
Decatur police punch and arrest black business owner who called to report a robbery.
---

## Location

Decatur, AL

## Date

March 15th

## Description

Armed, black business owner mistaken for robber, punched by white Alabama cop

## Links

https://www.al.com/news/2020/06/decatur-police-officer-punches-liquor-store-owner-who-reported-robbery.html

**Comment by samgoldman** [comment]
Closing based on the repository [contribution guidelines](https://github.com/2020PB/police-brutality/blob/master/CONTRIBUTING.md):

> Only events related to the 2020 George Floyd protests in the United States.
> No old events or events not related to the protests.
