### ISSUE TITLE
unfamiliar with github

### ISSUE THREAD

**Issue by AIDE-D-BH** [2020PB/police-brutality#49]
After following the 'Submission Guide' I am shown a 'Comparing changes' page showing my additions. However, my additions are not reflected on the repo. Not even on my fork of the repo that it creates. Can I get some clarification on what needs to be done after clicking 'Propose file change' in order to add incidents to the repo?

**Comment by 2020PB** [comment]
Apologies, I will update the submission guide soon.

When you get to the comparing changes page, you should be able to just click create pull request to submit the edit proposal.

**Comment by AIDE-D-BH** [comment]
Done, thanks for the help, and apologies for the noob question.
