### ISSUE TITLE
Incident -- large google spreadsheet

### ISSUE THREAD

**Issue by jessesquires** [2020PB/police-brutality#501]
This spreadsheet has started circulating. I'm sure there are duplicates with what is already listed on the site, but there are likely many that are not already here.

https://docs.google.com/spreadsheets/u/1/d/1YmZeSxpz52qT-10tkCjWOwOGkQqle7Wd1P7ZM1wMW0E/htmlview

**Comment by emarcey** [comment]
Has been merged. Thanks!
