### ISSUE TITLE
Adding tags to entries

### ISSUE THREAD

**Issue by melloc** [2020PB/police-brutality#536]
(It looks like this started getting discussed in #164, but OP closed it, so I figured I'd make a new issue.)

It would be nice if entries had tags that could help people find related submissions more easily. Some examples of tags based on videos I've seen:

- By victim in video:
  - `celebrity`
  - `child`
  - `elderly`
  - `journalist`
  - `medic`
  - `politician`
  - `pregnant`
- By method of assault/weapons/tools used by police:
  - `baton`
  - `beanbags`
  - `bike`
  - `flash-bangs`
  - `headlock`
  - `kick`
  - `knee-on-kneck`
  - `marking-rounds`
  - `pepper-ball`
  - `pepper-spray`
  - `punch`
  - `rubber-bullets`
  - `shield`
  - `shove`
  - `taser`
  - `tear-gas`
  - `vehicle`
  - `wooden-bullets`
- Other possible tags:
  - `arrest`
  - `helicopter`
  - `threat`

**Comment by ed42311** [comment]
Not sure if that helps, but if it does:  https://github.com/2020PB/police-brutality/pull/543 

if not just close it out

**Comment by triton11** [comment]
Nice!

**Comment by emarcey** [comment]
This has been added. Thanks for the suggestion
