### ISSUE TITLE
Sharing a similar project

### ISSUE THREAD

**Issue by charlex** [2020PB/police-brutality#546]
Hi, I started something like this in my personal capacity, and figured some of what I did might be of inspiration to you all in terms of schema, form layout, and data (albeit small amount of data) etc.

Form:
https://airtable.com/shr2wmgGksh7qUjB9

List:
https://airtable.com/shrTfx4vluaEhtpw6/tblVYBxJyu2osenUA

Gallery:
https://airtable.com/shrAn9iCR4hJOkvXr/tblVYBxJyu2osenUA

PoliceOne.com scraper:
https://github.com/charlex/cops-database

PoliceOne agencies scraped:
https://airtable.com/shrAEQpK6utK5C79U

**Comment by emarcey** [comment]
Thanks! We'll pull it into our review tool and try to add as much as we can. Feel free to check out our Data APIs to integrate our data into yours (also happy to help try and export some in a format useful to you)
