### ISSUE TITLE
Proper documentation methods

### ISSUE THREAD

**Issue by slharrow** [2020PB/police-brutality#568]
This is a fantastic start! However, to be most effective, I recommend adding: 

1. direct linking with other repositories/Google Drives/etc. 
   -by networking, it can create a positive feedback loop that supports the documentation and the 
   movement overall 
2. addition of the actual video files, photos, and details of each incident report 
    -independent backup of files and information will make this resource stronger, rather than relying on the posts on twitter, reddit, etc which may be deleted, removed, or adulterated by intentional or unintentional means

**Comment by dostran4** [comment]
Closing, as we link to other repositories and front end websites that have videos.
