### ISSUE TITLE
Where can I see a list of linked videos?

### ISSUE THREAD

**Issue by zylstra** [2020PB/police-brutality#569]
Where can I see a list of clickable video links and other data?

**Comment by jlev** [comment]
There is a `data-build` branch with CSV and JSON files that are automatically built on each commit to master. https://github.com/2020PB/police-brutality/blob/data_build/all-locations.csv

Several users have also created APIs for integrating with websites, which may include other information (lat/lon, tags, links to backed up media, etc)

**Comment by zylstra** [comment]
I do not see any clickable links to videos on the page you linked to.

**Comment by 949mac** [comment]
> I do not see any clickable links to videos on the page you linked to. I do see what look like links but they are not clickable.

Hello, I can provide a list of links in mp4 format. Will this be helpful? Can I provide this list you in JSON format or is CSV preferred?

**Comment by zylstra** [comment]
Hi, 949mac, if you can provide an automatically updating version on the web that everyone can access it will be helpful, otherwise, no.

**Comment by dostran4** [comment]
Closing this, since there are a couple of links to websites that have the videos readily available.
