### ISSUE TITLE
SUGGESTION: Add Topics

### ISSUE THREAD

**Issue by TheEvilSkeleton** [2020PB/police-brutality#584]
hello, sorry for the offtopic issue

i'm a big fan of this project and i have showed it to my friends, but i would like to suggest to add topics so it can gain more popularity; e.g. `cops police police-reports justice`, etc.

just press on "Manage topics", at the description area and then it will let you add the topics

![image](https://user-images.githubusercontent.com/50847364/84526135-c5bae880-acaa-11ea-8e7e-094311ac9fcb.png)

**Comment by emarcey** [comment]
Done! Sorry for the delay
