### ISSUE TITLE
Automate spellchecking with Typo CI

### ISSUE THREAD

**Issue by maxspencer** [2020PB/police-brutality#595]
I thought it might speed up reviews if we automated the spell-checking part. There's this free GitHub app called Typo Cl we could install on the repo and it would run its checks on each new PR automatically (with options to exclude certain files).

https://github.com/marketplace/typo-ci

Might be one you have to handle as owner of the repo @2020PB?

**Comment by dostran4** [comment]
Closing as we now have some spellchecking files for common misspellings.
