### ISSUE TITLE
Atlanta, Georgia

### ISSUE THREAD

**Issue by Bex3** [2020PB/police-brutality#600]
## Location

Atlanta, GA

## Date

June 12, 2020

## Description

27-year-old Rayshard Brooks fell asleep in his parked car in the drive-thru lane of a Wendy's. When cops arrived Rayshard failed a field sobriety test and resisted arrest, he attempted to grab the taser and started fleeing. Cops shot him 3 times in the back, he died during emergency surgery. 

## Links
https://twitter.com/DabbityMcyeet/status/1271856090079166466
https://www.tmz.com/2020/06/13/atlanta-police-fatally-shoot-black-man-wendys/
https://abcnews.go.com/US/man-dead-shot-atlanta-police-gbi-investigating/story?id=71232363

**Comment by emarcey** [comment]
Non-protest, but I will put it in our backlog

**Comment by emarcey** [comment]
In the backlog. Will include once we've finished adding all the protest footage we have
