### ISSUE TITLE
Incident in Minneapolis, MI

### ISSUE THREAD

**Issue by joshua-s** [2020PB/police-brutality#601]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location

Minneapolis, MI

## Date

~June 8th

## Description

Police drive by pepper spraying peaceful protestors who are not on the street

## Links

* https://www.tiktok.com/@montygeer/video/6835674436054568198

**Comment by emarcey** [comment]
We already have this as `mn-minneapolis-3`
