### ISSUE TITLE
New Project using your list:

### ISSUE THREAD

**Issue by lucasvocos** [2020PB/police-brutality#607]
https://www.defund-police.org/

**Comment by xloem** [comment]
Hey do you have the capability to add a link to this in a pull request?  I am not a maintainer but it would help people find it and help preserve the history.

**Comment by lucasvocos** [comment]
Yep, absolutely

**Comment by dostran4** [comment]
@emarcey  Can we add this website to the list of Front-End sites? They are still updating using our data, as well as providing links to other useful activist things.

**Comment by emarcey** [comment]
https://github.com/2020PB/police-brutality/pull/709

We should've closed this a while ago. This is a decision we came to in the Discord a while back
