### ISSUE TITLE
Incident

### ISSUE THREAD

**Issue by apollogio11** [2020PB/police-brutality#616]
Bethel, Ohio

A man was protesting for black lives matter. He was surrounded by white people who were against the movement. He was talking to a cop when a random man punched him in the side of the face. The cop just stood there and did nothing. 

This is all the information I have. Here is a link to the video.
https://vm.tiktok.com/J1xw8Go/

**Comment by ed42311** [comment]
This may be another angle from this post:  https://github.com/2020PB/police-brutality/blob/master/reports/Ohio.md#bethel

The youtube video / local news coverage is dated June 15, 2020:  https://www.youtube.com/watch?v=6GVbOjgBUCc

The tiktik video above is dated 4 days ago so those two dates would coincide.  The angle captured here is more direct.  

On a side note, both videos show police failure to act, they are not directly linked to police brutality.  The aggressive actions are perpetuated by counter-protestors.  This comment is not meant to downplay the peaceful actions of the protestors, only to discuss clarity of purpose and establish consistency in the database.

Related somewhat to this comment: https://github.com/2020PB/police-brutality/issues/681

**Comment by emarcey** [comment]
We've got this incident included
