### ISSUE TITLE
Incident in Denver, CO

### ISSUE THREAD

**Issue by joshua-s** [2020PB/police-brutality#617]
## Location

Denver, CO

## Date

May 29th, 2020

## Description

Car pulls up to corner, apparently cops tear gas occupants off camera. Boyfriend gets out of car and starts calling the cops out, saying his girlfriend is pregnant. They open fire with what appears to be pepper bullets.## Location

## Links

Found in this tweet: https://twitter.com/morphonios/status/1268370620418527232

Original source: https://www.youtube.com/watch?v=S4-5pbk_Vpk&feature=youtu.be&t=9159

**Comment by 01210210** [comment]
This has already been reported as co-denver-8

**Comment by joshua-s** [comment]
@01210210 thanks for the update. Closing this
