### ISSUE TITLE
Police driving through crowd of protesters in Richmond, VA

### ISSUE THREAD

**Issue by watsonkh** [2020PB/police-brutality#651]
## Location

Richmond, Virginia

## Date

June 15th

## Description

Police drove through a crowd of protesters

## Links

https://twitter.com/BreRVA/status/1271982379180138502

https://www.richmond.com/news/local/crime/attorneys-weigh-in-on-legality-of-richmond-police-officer-driving-through-protesters/article_dca22ade-ca21-543c-90a2-d57aa7acb351.html

**Comment by emarcey** [comment]
https://github.com/2020PB/police-brutality/pull/650
