### ISSUE TITLE
Police detaining innocent protester, sparking violence in Richmond, Virginia

### ISSUE THREAD

**Issue by watsonkh** [2020PB/police-brutality#652]
## Location

Richmond, Virginia

## Date

June 15th

## Description

Police grab protestor and pepper spray crowd, sparking violence.

## Links

Initial incident:
https://www.reddit.com/r/2020PoliceBrutality/comments/ha18d6/the_moment_police_in_richmond_va_escalated_last/

https://www.nbc12.com/2020/06/15/police-use-tear-gas-protesters-during-standoff-near-richmond-police-headquarters/

**Comment by emarcey** [comment]
We have this one already: https://github.com/2020PB/police-brutality/blob/master/reports/Virginia.md#police-fire-tear-gas-and-rubber-bullets-at-peaceful-protest--june-15th
