### ISSUE TITLE
Incident in Portland, Oregon

### ISSUE THREAD

**Issue by PNWResistance** [2020PB/police-brutality#669]
INSTRUCTIONS: Add the key information about the incident under the headings Location, Date, Description and Links below and then click the green "Submit new issue" button.

If you are unsure about any details then please write "Unknown" under that heading.

---

## Location
Portland, OR

## Date

June 15th, 2020 at approximately 12:15am

## Description

Portland Police declares a zone of no-assembly that encompasses almost all of Downtown Portland. Portland Police can be heard giving orders to reputable journalist an order to disperse the area, telling them the constitutional 1st amendment to Freedom of Press is suspended. 

## Links

Twitter: https://twitter.com/TheRealCoryElia/status/1272427882359353344

**Comment by emarcey** [comment]
Added
