### ISSUE TITLE
Missing evidence for CA-oakland-1

### ISSUE THREAD

**Issue by ContributingThrowaway** [2020PB/police-brutality#679]
The video for CA-Oakland-1 is missing. (The sole link is to a reddit post that has since been removed.)

**Comment by 01210210** [comment]
Alternative video of the incident here: https://tuckbot.tv/#/watch/gttdkj (taken from reddit thread)

**Comment by ContributingThrowaway** [comment]
Thanks -- that mirror was giving me a 404 when I checked it a few days ago but it seems to be working now.
