### ISSUE TITLE
Potentially inappropriate entries

### ISSUE THREAD

**Issue by ContributingThrowaway** [2020PB/police-brutality#681]
Are the following entries examples of police brutality, as defined for this project? 

CA-losangeles-24: Police use metro buses to transport arrestees

CA-walnutcreek-1: A police vehicle's path is blocked by nonviolent protesters obstructing a highway. Police tell the protesters to move out of the way. Police say something to protesters that sounds (after being garbled by the speaker) like "if you do not move you will be dead" but that later-released video seems to indicate was "if you do not move you will be gassed;" when protesters do not disperse, the police deploy tear gas.

CO-Denver-4: A police armored personnel carrier's path is blocked by a nonviolent protester holding a sign. Police officers get out and fire, apparently hitting the ground in front of the protester. (It seems like they were firing warning shots; it doesn't look as though any of the shots hit the protester.) Another officer is raising his weapon as the protester retreats around the side of the APC and it continues on its way.

I ask partly because I feel like the power of this project is in its clarity: here are well-documented incidents of officers doing totally indefensible things -- conducting illegal arrests; shooting people with rubber bullets for standing on their porches; beating people who aren't resisting arrest. I get the sense that the above incidents (esp. CO-Denver-4 and CA-losangeles-24) are much less clear-cut.

**Comment by 01210210** [comment]
I agree that events that fail to meet a minimum threshold of police brutality or misconduct should be removed. I believe that threshold should be low, but not low enough so that the 3 events cited above qualify. I am in favor of their removal.

**Comment by sprucelee** [comment]
I disagree with removing CA-walnutcreek-1. I think the use of teargas at all it counts as "excessive force" since it is illegal in warfare according to the Geneva Protocol. The fact that it has not been made illegal for use on civilians is what makes it brutality.

**Comment by ContributingThrowaway** [comment]
I disagree with a blanket position that "tear gas implies police brutality," for three reasons:

1. On a moral level, suppose police need to disperse a crowd. They could use paintballs, rubber bullets, or pepper balls (all perfectly legal in war), but those are (I think) more dangerous than tear gas. Alternatively, police could don riot gear and shove the crowd back with shields. That presents a logistical problem -- police are almost always outnumbered in crowd control situations, and often there aren't enough of them to hold a line of officers with shields. They could use batons or pepper spray, but that doesn't seem to me much better than tear gas. And engaging at close range increases the likelihood of escalation. (Of course, tear gas is force, and like any use of force it needs to be justified.)

2. On a pragmatic level, if our policy is that "all uses of tear gas are police brutality," we'll be flooded with literally hundreds of incidents that are nothing but "police use tear gas." That seems to me like a problem.

3. On a PR level, the power of this project is its clarity. No human being with a soul can look at officers beating peaceful protesters and think "this is fine." I think many people (for better or for worse) can look at officers tear gassing a crowd for a clear, defensible law enforcement reason and think it's fine.

Of course, these are just abstract arguments against an "all tear gas is brutality" policy. In this particular case, we could decide that clearing a highway of peaceful protesters isn't a clear, defensible law enforcement reason in the first place. (I'm not sure I agree with that line of reasoning, but we might decide that.) We might also decide that covering a highway with a thick cloud of billowing, blinding gas is an odd way to make it safe for motorists. I would definitely understand including it for that reason. (I'm not sure how long tear gas stays in the air...)

If there's no objection to removing ca-losangeles-24 and co-denver-4, I'll remove them later today.
