### ISSUE TITLE
A website for accessbility to these records

### ISSUE THREAD

**Issue by Brydom** [2020PB/police-brutality#71]
Hey! I'd like to offer to make a website for easier access and potential mirror of the original videos within that website.

All of the data is consistent and nicely formatted so the markdown files should be able to be parsed simply.

**Comment by mrweiner** [comment]
@Brydom just so you know, there's currently a site at https://2020policebrutality.netlify.app/ and a conversation about mirroring videos at https://github.com/2020PB/police-brutality/issues/32
