### ISSUE TITLE
Front end help needed to make the gallery prettier

### ISSUE THREAD

**Issue by ubershmekel** [2020PB/police-brutality#740]
This gallery showcases projects that use the 2020pb api: https://pb2020gallery.netlify.app/

It works, but it's programmer art. Would be nice if a front end designer or developer could make it better. The source code is at: https://github.com/ubershmekel/pb2020gallery

**Comment by Thexumaker** [comment]
I'm just getting into Front end design but could I work on improving the front end of the site?

**Comment by ubershmekel** [comment]
That would be awesome. Thank you @Thexumaker

**Comment by Thexumaker** [comment]
Just sent in some changes, let me know if it works or not

**Comment by ph-ct** [comment]
This is my main github account but I can help with some react programming for the frontend if you need.  Just let me know.  I have over a decade of professional programming experience and recently have a ton of time recently :), I just don't want people connecting some of my other work and people worked with in the past can be connected to other github account so I'm using this one.  I'll clone that repo mentioned above but just let me know and if you want, I can probably setup a aws account and get it wired up to amplify and that way we can host it there cheaply.  Plenty of options, just wondering what the requests are.

**Comment by ubershmekel** [comment]
Thank you @ph-ct I believe @Thexumaker made a nice update to the gallery. We don't need to re-host anything at the moment as far as I know. If you'd like to look at the sites mentioned at the top of this issue and make a PR to make it look nicer, that would be cool. For now I think this ticket can be closed, but feel free to comment if it makes sense to re-open.
