### ISSUE TITLE
Web App for Easier Data Entry

### ISSUE THREAD

**Issue by sshh12** [2020PB/police-brutality#76]
I think there's a lot of friction in people using github itself for data entry.

@2020PB would you be interested in a web app that streamlines the process?

I'm thinking (2 day build):
1. A single page form guides users through the Contribution Guidelines
2. On submit a GitHub bot creates a pr and labels it something like 'pending-review'
3. PR manually checked & merged

Lmk what you think. Happy to help as a full-stack dev.

Edit: 
* Bot could also upload renders of visualizations of the datasets (I dunno maybe a word cloud, per state stats, etc)

**Comment by Brydom** [comment]
I'd be happy to contribute to this as well!

**Comment by Lalaland** [comment]
How about just using a google form?

**Comment by nickatnight** [comment]
Also happy to help here <3

**Comment by sshh12** [comment]
@Lalaland I agree webapp maybe over engineering it. 

I believe the GitHub automations would still be useful though, thoughts?

@2020PB Fill free to tag on any other web/tech/eng tasks here, looks like we already have a team of engineers (:

**Comment by sshh12** [comment]
Attaching relevant issues: #106 #114 #103 #101

**Comment by mnlmaier** [comment]
Would be happy to help aswell – I would love creating an interactive map. See #133

**Comment by maxspencer** [comment]
> How about just using a google form?

This seems like a good first step if only to quickly prototype the optimal design/structure of the form. Can always make a better v2 afterwards.

**Comment by sshh12** [comment]
Deferring to #141 to avoid overlapping issues/projects.

**Comment by ubershmekel** [comment]
Making note of this here just in case it's relevant to anyone that wants to contribute:

The data build is live. Every commit to master will regenerate these files in the branch `data_build`.

* https://github.com/2020PB/police-brutality/tree/data_build
* The best data will always be at https://raw.githubusercontent.com/2020PB/police-brutality/data_build/all-locations.json
* If you want to change anything about how this data is generated then look at https://github.com/2020PB/police-brutality/tree/master/tools
