### ISSUE TITLE
Incident in Chattanooga, TN

### ISSUE THREAD

**Issue by silentsilas** [2020PB/police-brutality#796]
## Location

Chattanooga, TN

## Date

May 31st, 2020

## Description

Two protestors were taking down a banner strung from two light posts in front of the Hamilton Court House, and inadvertently knocked down one of them in the process. They were promptly arrested for "vandalism" and the Sheriff's office used it as justification to fire tear gas into the crowd of peaceful protestors. Chattanooga Police were not aware tear gas was going to be deployed and said it wasn't justified. Sheriff's office defended their use of it. The video footage linked should show that the protestors had _no_ intention of vandalizing and were not verbally assaulting officers, contrary to most of Chattanooga's local news.

## Links

https://www.chattanoogan.com/2020/5/31/409849/Protestors-Face-Off-With-Law.aspx
https://www.youtube.com/watch?v=Jkj3EfktVkM (The two protestors taking down the banner, and the light post falling over)
https://www.youtube.com/watch?v=MeIV1kSsPZg (Protestors chanting "Hand's up, don't shoot" in response to armed officers arriving on scene)
https://www.youtube.com/watch?v=rq_2YSLn4FE (The shooting of tear gas)
https://www.youtube.com/watch?v=-kuD_naCPzo (Aftermath)

**Comment by emarcey** [comment]
I opened a PR! We have very little from Chattanooga, so if you have other incidents and/or know of any reporters covering the scene, please post them here. Thanks!

**Comment by emarcey** [comment]
Merged!
