### ISSUE TITLE
Incident in Orlando, Florida

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#802]
Police assault woman in car

---

## Location

Orlando, Florida

## Date

June 3rd

## Description

Police stop and harass woman in car. They force their way into the car and assault her.

## Links

https://twitter.com/edgarcomellas/status/1268555233065668608

**Comment by amardeshbd** [comment]
I'm looking into this report. Will open a PR shortly.

**Comment by emarcey** [comment]
Oh I assigned myself to ones I had started working on

**Comment by emarcey** [comment]
#817 

I think the Des Moines issue is the only one that needs a new PR

**Comment by amardeshbd** [comment]
@emarcey Okay! sounds good! 

While looking into it I found related links
* https://www.wdbo.com/news/local/video-shows-orange-county-deputy-smashing-woman-window-after-refusing-leave/2JrFiuwJgtkVzGJqXrLS7I/


Also, I have a question regarding the V2 data dump. Some of the links has descriptions, however, the [incident-report-format](https://github.com/2020PB/police-brutality/blob/master/CONTRIBUTING.md#incident-report-format) does not have a way to provide that info. Let me know if I missed it. Thanks
