### ISSUE TITLE
Increase the minimum number of reviewers for Incident Pull Requests

### ISSUE THREAD

**Issue by DerTiedemann** [2020PB/police-brutality#804]
As more people are brought into the review process (and due to high demand maybe not as thoroughly checked see #750 ), it would probably be a good idea to have a PR reviewed by at least 2 different people to ensure accurate, unbiased and high quality data. Two people here is arbitrary and should be adjusted based on the number of reviewers.

Besides kudos to all contributors who a working to cleanse the data set of faulty entries!

**Comment by dostran4** [comment]
Closing, since we don't have enough reviewers right now.
