### ISSUE TITLE
Incident in Ridgewood, New Jersey

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#825]
---

## Location

Ridgewood, New Jersey

## Date

July 4th

## Description

Police arrest underage protestor

## Links

https://mobile.twitter.com/RW4BL/status/1279536407577575424
https://twitter.com/zellieimani/status/1279495928144158720

**Comment by ContributingThrowaway** [comment]
Context: as far as I can tell, arrestee was Thriamargret Bernabe, age 22; she was the only person arrested that day. She was arrested at 12:30 for blocking a road and released at 4PM.

https://www.northjersey.com/story/news/bergen/ridgewood/2020/07/04/black-lives-matter-protest-ridgewood-nj-arrest/5376897002/
https://patch.com/new-jersey/ridgewood/black-lives-matter-protester-wouldnt-leave-road-ridgewood-chief

**Comment by emarcey** [comment]
Okay yeah this is a questionable inclusion. I'm gonna close this issue
