### ISSUE TITLE
Incident in Unknown

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#828]
Try to find location/date for this incident: https://www.reddit.com/r/PublicFreakout/comments/hla9m6/film_the_cops_not_the_protesters/

If you can track it down, check if it's a duplicate
---

## Location

Unknown

## Date

Unknown

## Links

https://www.reddit.com/r/PublicFreakout/comments/hla9m6/film_the_cops_not_the_protesters/

**Comment by ContributingThrowaway** [comment]
What about this incident do we think constitutes police brutality/misconduct?

**Comment by emarcey** [comment]
Oops I must've made a mistake copying links
