### ISSUE TITLE
Incident in Gustine, CA

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#829]
---

## Location

Gustine, CA

## Date

June 30th

## Description

Right wing counter protestors beat children while police stand idly by. 

Looks like another case of selective enforcement.

## Links

https://twitter.com/greg_doucette/status/1279473878335655936
https://twitter.com/greg_doucette/status/1279449819497615360
https://www.mercedsunstar.com/news/local/article243914827.html

**Comment by ContributingThrowaway** [comment]
I'll add later today.
