### ISSUE TITLE
Incident CO-Denver-6 not currently adequately substantiated

### ISSUE THREAD

**Issue by ContributingThrowaway** [2020PB/police-brutality#834]
Incident CO-Denver-6 says that police turned off their body cams then fired tear gas at protesters. The linked video shows tear gas being thrown, but does not show body cams being turned off. Do we have evidence of that, beyond some guy on twitter saying so? If not, we should at least qualify the statement ("Police tear gas protesters after allegedly turning off body cameras"). We should also consider removing the incident entirely -- we have no context for why tear gas was deployed.

**Comment by emarcey** [comment]
Tear gas is always police brutality. Asthmatic people have died. It can cause miscarriages. Evidence is emerging that numerous protestors have had disruptions to/irregular menstrual cycles. 

Feel free to change the body camera bit to "allegedly," or poke around the news and see if you can find anything

**Comment by emarcey** [comment]
#840
