### ISSUE TITLE
Sexual Assault of a protester in Miami, Florida

### ISSUE THREAD

**Issue by RooneyMcNibNug** [2020PB/police-brutality#837]
## Location

Miami, Florida

## Date

July 1st

## Description

Miami Police officer is seen grabbing the breast of a protester as she is being escorted to a police vehicle. She was arrested during a protester for unknown reasons, handed off to multiple officers - none of who read her Miranda rights or told her why she was being detained.

"While she waited at the station in handcuffs, Barnes says, an officer took a photo of her on his personal cell phone. He told her he was going to send it to a cop she had an altercation with at a protest the day before."

## Links

https://www.miaminewtimes.com/news/video-shows-miami-police-grab-breast-of-protester-11661608

**Comment by emarcey** [comment]
#817
