### ISSUE TITLE
Assault in New York City, New York

### ISSUE THREAD

**Issue by RooneyMcNibNug** [2020PB/police-brutality#838]
## Location

New York City, New York

## Date

May 29th, 2020

## Description

A young woman walks up to/past an NYPD officer (not sure if she was trying to cross the street or speak with the officer) and is immediately and strongly pushed away, hard enough where her head hits the pavement. She later explains that she suffered a concussion and seizures due to the assault.

e.g. Police pepper spray kneeling protestors

## Links

https://thehill.com/homenews/state-watch/500269-nypd-officer-under-investigation-following-video-of-female-protester
https://twitter.com/whitney_hu/status/1266540710188195843

**Comment by emarcey** [comment]
https://github.com/2020PB/police-brutality/blob/master/reports/New%20York.md#police-shove-woman-to-the-ground-inducing-a-seizure--may-29th

This incident is covered
