### ISSUE TITLE
Officer Spitting on detained person, Richmond, Virgina

### ISSUE THREAD

**Issue by RooneyMcNibNug** [2020PB/police-brutality#839]
## Location

Richmond, Virginia

## Date

June 2nd, 2020

## Description

During a pandemic, a police officer spits on a detained and cuffed protester positioned underneath them. After the person filming it and other protesters mention that they have filmed the officer committing the act, the officer spits on the detained person once again.

## Links

https://twitter.com/BrutumF/status/1267712284740194304
https://god.dailydot.com/richmond-police-spit-on-protestor/

**Comment by RooneyMcNibNug** [comment]
There is a lot of talk about the officer spitting into the grass and not on the detained protester: https://www.richmond.com/video/news/in-slowed-down-and-enlarged-version-of-facebook-video-officer-appears-to-spit-into-grass/video_da8c3c3b-4bf1-510c-9f33-9bd1d2bf11d3.html

It might be worth doing a FOIA to obtain any body-camera video/audio of the officer during this, but their identity is unknown.

**Comment by emarcey** [comment]
https://github.com/2020PB/police-brutality/blob/master/reports/Virginia.md#officer-spits-on-detained-protestor--june-1st

This incident is covered
