### ISSUE TITLE
Incident in Seattle, WA

### ISSUE THREAD

**Issue by BFirfer** [2020PB/police-brutality#855]
---

## Location

Seattle, WA

## Date

July 2nd

## Description

Police assault protesters with shields, tackle people and use an arm on the neck to get them to let go of their bike.

## Links
https://www.reddit.com/r/CapHillAutonomousZone/comments/hjuwkk/bop_shield_cop_goes_agro_on_the_bike_brigade/
https://twitter.com/zmboop/status/1278640469635764225

**Comment by 2020PB** [comment]
We added this one today, actually!

https://github.com/2020PB/police-brutality/blob/master/reports/Washington.md#violent-arrests-made-at-protests-near-chop--july-2nd

**Comment by BFirfer** [comment]
The footage I added included the shield cop pushing people, which does not
seem to be in any of the current footage?
https://twitter.com/itsjosephryan/status/1278627952914075648

**Comment by emarcey** [comment]
Ah, I see. I will add that
