### ISSUE TITLE
OR-Salem-1 evidence

### ISSUE THREAD

**Issue by ContributingThrowaway** [2020PB/police-brutality#881]
OR-Salem-1 claims that the people warned by police were Proud Boys. Do we have evidence of that, beyond the say-so of the person who posted it?

**Comment by emarcey** [comment]
The Buzzfeed article is enough confirmation for me. They were guarding a certain hair salon that was known to have been protected by white supremacist militia. But feel free to rephrase in a more neutral way

**Comment by dostran4** [comment]
https://twitter.com/benni1028/status/1268903014955462656?s=19

This picture indicates that at least one person present was a Proud Boy at some point, but it doesn't look like anything cohesive, organized, or endorsed by them.

**Comment by emarcey** [comment]
I agree, I don't think it was a coordinated or sponsored Proud Boy event, but I do think that
a) There are definitely Proud Boys and likely other fascists present
b) Police made a concerted effort to warn them and treated them differently from BLM protestors

**Comment by dostran4** [comment]
Made a PR to modify the language so we aren't making claims without evidence
