### ISSUE TITLE
Incident in Grand Rapids, Michigan

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#898]
---

## Location

Grand Rapids, Michigan

## Date

July 12th

## Description

Police drag protestor through the street

## Links

https://twitter.com/greg_doucette/status/1283027373018013699
https://twitter.com/greg_doucette/status/1283027125805735939

**Comment by Murkantilism** [comment]
@emarcey 2nd link appears to be from Portland OR 2 days prior to 1st link, should that be a separate issue, or do you know if that incident has already been added?

**Comment by emarcey** [comment]
@Murkantilism I think you may have scrolled up or something. That link should take you to an incident marked 770

**Comment by Murkantilism** [comment]
@emarcey after checking again, it's a Twitter or Chrome bug maybe. Middle mouse or left _clicking_ the link takes me to 769 in Portland OR, but copy/pasting the link takes me correctly to 770 lol \*shrug*.

**Comment by emarcey** [comment]
Honestly those Greg Doucette threads wreak havoc on my browser too - might be better to link Greg's sources in the actual incident. I don't think Twitter was really anticipating these 1,000 tweet threads

**Comment by Murkantilism** [comment]
@emarcey the relationship between the two videos is unclear to me (other than taking place in the same square). Should I write it as two separate incidents?

The distance from officers in the 2nd video, shot from far above, makes it difficult to confidently tell if any of the same officers are seen assaulting (shoving) civilians in the first video.

**Comment by emarcey** [comment]
https://mobile.twitter.com/OfficAlyNicole/status/1283181085577420810

I think this thread establishes it pretty well as a single series of events. The incident can have a few aspects, but it appears to me to be a flow of connected events

**Comment by emarcey** [comment]
But if it still really seems like two distinct incidents to you, I think you've probably been looking at the footage more, so feel free to make a judgment call and we can rehash this in the PR. 

I'd say generally err on the side of caution (potentially collapse incidents rather than accidentally duplicate)

**Comment by Murkantilism** [comment]
Nah that link makes the timeline of events much clearer, thanks.

**Comment by emarcey** [comment]
Cool cool. Just a general tip for the Greg doucette threads: digging into the profile from whom he's sourcing the footage is a better way of figuring out the context and timeline of events

**Comment by Murkantilism** [comment]
@emarcey ready for initial review
