### ISSUE TITLE
Incident in Iowa City, Iowa

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#902]
---

## Location

Iowa City, Iowa

## Date

June 3rd

## Description

Supplementary footage io-iowacity-1

## Links

https://www.reddit.com/r/IowaCity/comments/gwx86v/another_angle_of_the_police_firing_upon_us/
https://www.reddit.com/r/IowaCity/comments/gwml8n/state_police_gassing_citizens/
https://www.reddit.com/r/IowaCity/comments/gwaqzx/from_a_facebook_livestreamseems_like_peaceful/
https://www.reddit.com/r/IowaCity/comments/gwc763/iowa_city_pd_gassed_and_flashbanged_their_own/

**Comment by Murkantilism** [comment]
Ready for review: https://github.com/2020PB/police-brutality/pull/971
