### ISSUE TITLE
Move il-chicago-2 to Cleveland

### ISSUE THREAD

**Issue by emarcey** [2020PB/police-brutality#966]
Protester shot in head with rubber bullet | May 30th
Images of a protester who was shot with a rubber bullet in the head.
This incident is listed under Chicago but I believe it happend in Cleveland. The persons bio says "cleveland' which is what I assume she means when saying 'CPD'

**Comment by dostran4** [comment]
https://twitter.com/captaingayhab/status/1270099530420301831?s=20

Very sure you're correct on this one. She retweeted the above tweet about Cleveland Heights, it's Cleveland in her Bio, she mentions Cleveland in another tweet:

https://twitter.com/LUVRGRLLANI/status/1272631357982814211?s=20

**Comment by dostran4** [comment]
Made a PR to reflect these changes.

**Comment by emarcey** [comment]
@dostran4 I haven't seen a PR? Can you link it to me?

**Comment by emarcey** [comment]
nvm I found it
